import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,readFileSync,writeFileSync,readdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import path from 'node:path';import ts from 'typescript';
const temp=mkdtempSync(path.join(tmpdir(),'tufi-auth-'));
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
globalThis.testEnv={ADMIN_PROFILE_ID:'owner',AUTH_PEPPER:'test-only-pepper-never-used-in-production'};
globalThis.testHeaders=new Headers();globalThis.legacyUser=null;
writeFileSync(path.join(temp,'server.mjs'),compile(readFileSync('lib/server.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.testEnv;")));
writeFileSync(path.join(temp,'auth.mjs'),compile(readFileSync('lib/auth.ts','utf8').replace("import {headers} from 'next/headers';","const headers=async()=>globalThis.testHeaders;").replace("import {env} from 'cloudflare:workers';","const env=globalThis.testEnv;").replace("from './server'","from './server.mjs'")));
const rewrite=s=>s.replace("import {getChatGPTUser} from '@/app/chatgpt-auth';","const getChatGPTUser=async()=>globalThis.legacyUser;").replace("from '@/lib/server'","from './server.mjs'").replace("from '@/lib/auth'","from './auth.mjs'").replace("from '@/lib/email'","from './email.mjs'").replace("from './email-actions'","from './email-actions.mjs'");
writeFileSync(path.join(temp,'email.mjs'),compile(readFileSync('lib/email.ts','utf8').replace("from './auth'","from './auth.mjs'")));
writeFileSync(path.join(temp,'email-actions.mjs'),compile(rewrite(readFileSync('app/api/auth/email-actions.ts','utf8'))));
writeFileSync(path.join(temp,'route.mjs'),compile(rewrite(readFileSync('app/api/auth/route.ts','utf8'))));
writeFileSync(path.join(temp,'admin.mjs'),compile(rewrite(readFileSync('app/api/admin/route.ts','utf8'))));
const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+file,'utf8'));
globalThis.testDB={async batch(statements){sql.exec('BEGIN');try{const out=[];for(const stmt of statements)out.push(await stmt.execute());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}},prepare(query){let args=[];const stmt=sql.prepare(query);return {async execute(){if(/^SELECT/i.test(query))return {results:stmt.all(...args),meta:{changes:0}};const r=stmt.run(...args);return {results:[],meta:{changes:Number(r.changes)}}},bind(...a){args=a;return this},async first(){return stmt.get(...args)||null},async all(){return {results:stmt.all(...args)}},async run(){const r=stmt.run(...args);return {meta:{changes:Number(r.changes)}}}}}};

globalThis.testEnv.DB=globalThis.testDB;
const auth=await import('file://'+path.join(temp,'auth.mjs'));
const route=await import('file://'+path.join(temp,'route.mjs'));
const admin=await import('file://'+path.join(temp,'admin.mjs'));
const password='fixture-password-2026';
globalThis.testEnv.ADMIN_PASSWORD_HASH=await auth.hashPassword(password);
let cookie='',ip='192.0.2.1';
const post=async(body,origin='https://tufi.test')=>{const h=new Headers({'origin':origin,'cf-connecting-ip':ip,'cookie':cookie});globalThis.testHeaders=h;const r=await route.POST(new Request('https://tufi.test/api/auth',{method:'POST',headers:h,body:JSON.stringify(body)}));const set=r.headers.get('set-cookie');if(set){assert.match(set,/HttpOnly; Secure; SameSite=Lax/);cookie=set.split(';')[0];globalThis.testHeaders.set('cookie',cookie)}return {status:r.status,body:await r.json(),set}};
assert.equal((await route.GET()).status,200);assert.equal((await (await route.GET()).json()).account,null);
assert.equal((await post({action:'register',role:'admin',name:'Intruder',password})).status,400);
assert.equal((await post({action:'register',role:'student',name:'Alice',password},'https://evil.test')).status,403);
const registered=await post({action:'register',role:'student',name:'Alice',password,email:'owner@example.test',status:'approved'});
assert.equal(registered.status,201);assert.equal(registered.body.account.status,'approved');assert.match(registered.body.account.id,/^TF-[A-F0-9]{16}$/);
const studentId=registered.body.account.id,studentCookie=cookie;
const p=sql.prepare('SELECT p.*,a.password_hash FROM profiles p JOIN accounts a ON a.user_id=p.id WHERE a.login_id=?').get(studentId);
assert.equal(p.email,'');assert.equal(p.role,'student');assert.notEqual(p.password_hash,password);assert.equal(await auth.verifyPassword(password,p.password_hash),true);assert.equal(await auth.verifyPassword('wrong-password',p.password_hash),false);
assert.equal((await admin.GET()).status,403);
await post({action:'logout'});globalThis.testHeaders.set('cookie',studentCookie);assert.equal(await auth.getCurrentUser(),null);
assert.equal((await post({action:'login',role:'admin',login:studentId,password})).status,403);
assert.equal((await post({action:'login',role:'student',login:studentId,password:'wrong-password'})).status,401);
const waiting=await post({action:'login',role:'student',login:studentId,password});assert.equal(waiting.body.account.status,'approved');
await post({action:'logout'});
const owner=await post({action:'login',role:'admin',login:'adm123',password});assert.equal(owner.status,200);assert.equal(owner.body.account.role,'admin');assert.equal(owner.body.account.id,'ADM-0001');
const ownerCookie=cookie;assert.equal((await admin.GET()).status,200);
const disposableHash=await auth.hashPassword('disposable-password-2026');
sql.prepare("INSERT INTO profiles(id,name,email,role,requested_role,status) VALUES('disposable','Disposable','','student','student','approved')").run();
sql.prepare("INSERT INTO accounts(user_id,login_id,password_hash,created) VALUES('disposable','TF-DISPOSABLE',?,?)").run(disposableHash,Date.now());
sql.prepare("INSERT INTO sessions(token_hash,user_id,expires) VALUES('disposable-session','disposable',?)").run(Date.now()+60000);
let managed=await admin.POST(new Request('https://tufi.test/api/admin',{method:'POST',headers:{origin:'https://tufi.test'},body:JSON.stringify({action:'resetPassword',id:'disposable'})}));let managedBody=await managed.json();assert.equal(managed.status,200);assert.equal(managedBody.temporary.length,18);assert.equal(sql.prepare("SELECT COUNT(*) n FROM sessions WHERE user_id='disposable'").get().n,0);assert.equal(await auth.verifyPassword(managedBody.temporary,sql.prepare("SELECT password_hash FROM accounts WHERE user_id='disposable'").get().password_hash),true);
managed=await admin.POST(new Request('https://tufi.test/api/admin',{method:'POST',headers:{origin:'https://tufi.test'},body:JSON.stringify({action:'deleteUser',id:'disposable'})}));assert.equal(managed.status,200);assert.equal(sql.prepare("SELECT COUNT(*) n FROM profiles WHERE id='disposable'").get().n,0);assert.equal(sql.prepare("SELECT COUNT(*) n FROM accounts WHERE user_id='disposable'").get().n,0);
const approval=await admin.POST(new Request('https://tufi.test/api/admin',{method:'POST',headers:{origin:'https://tufi.test'},body:JSON.stringify({action:'user',id:p.id,role:'student',status:'approved',revision:0})}));assert.equal(approval.status,200);
const approved=await post({action:'login',role:'student',login:studentId.toLowerCase(),password});assert.equal(approved.body.account.status,'approved');assert.equal((await admin.GET()).status,403);
sql.prepare("UPDATE profiles SET status='blocked' WHERE id=?").run(p.id);assert.equal((await post({action:'login',role:'student',login:studentId,password})).status,403);
const teacher=await post({action:'register',role:'teacher',name:'Teacher',password});assert.equal(teacher.body.account.role,'teacher');assert.notEqual(teacher.body.account.id,studentId);assert.equal((await admin.GET()).status,403);
sql.prepare("UPDATE profiles SET role='teacher',status='approved' WHERE id=(SELECT user_id FROM accounts WHERE login_id=?)").run(teacher.body.account.id);assert.equal((await admin.GET()).status,403);
assert.equal((await post({action:'login',role:'admin',login:teacher.body.account.id,password})).status,403);
sql.prepare('UPDATE sessions SET expires=0').run();assert.equal(await auth.getCurrentUser(),null);
assert.equal((await post({action:'link',role:'student',name:'Legacy',password})).status,401);
sql.prepare("INSERT INTO profiles(id,name,email,status) VALUES('legacy','Old','verified@example.test','approved')").run();globalThis.legacyUser={userId:'legacy',email:'verified@example.test'};
const linked=await post({action:'link',role:'teacher',name:'Ignored',password});assert.equal(linked.status,201);assert.equal(linked.body.account.role,'student');assert.equal(linked.body.account.status,'approved');assert.equal(linked.body.account.name,'Old');assert.equal((await post({action:'link',role:'student',name:'Legacy',password})).status,409);
ip='192.0.2.2';for(let i=0;i<12;i++)assert.equal((await post({action:'login',role:'student',login:'TF-UNKNOWN',password})).status,401);assert.equal((await post({action:'login',role:'student',login:'TF-UNKNOWN',password})).status,429);
// Exercise real recovery handlers and provider request construction with an in-memory mail transport.
ip='192.0.2.10';
assert.equal((await post({action:'forgot',email:'missing@example.test'})).status,503);
const messages=[];let failMail=false;
globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');assert.equal(options.headers.Authorization,'Bearer test-email-key');assert.ok(options.headers['Idempotency-Key']);if(failMail)return new Response('{}',{status:503});messages.push(JSON.parse(options.body));return Response.json({id:'test-message'})};
Object.assign(globalThis.testEnv,{RESEND_API_KEY:'test-email-key',EMAIL_FROM:'Tufi <contas@example.test>',APP_ORIGIN:'https://tufi.test'});
const mailToken=()=>new URLSearchParams(new URL(messages.at(-1).text.match(/https:\/\/[^\s]+/)[0]).hash.slice(1)).get('token');
const emailUser=await post({action:'register',role:'student',name:'Email user',password,email:' User@escola.example.test '});
assert.equal(emailUser.status,201);assert.equal(emailUser.body.account.status,'approved');assert.equal(messages.at(-1).to[0],'user@escola.example.test');
const emailId=emailUser.body.account.id,verifyToken=mailToken();
assert.equal((await post({action:'login',role:'student',login:'user@escola.example.test',password})).status,401);
assert.equal((await post({action:'verify',token:verifyToken,password:'incorrect-password'})).status,401);
assert.equal((await post({action:'verify',token:verifyToken,password})).status,200);
assert.equal((await post({action:'verify',token:verifyToken,password})).status,400);
const byEmail=await post({action:'login',role:'student',login:'USER@ESCOLA.EXAMPLE.TEST',password});assert.equal(byEmail.status,200);assert.equal(byEmail.body.account.status,'approved');assert.equal(byEmail.body.account.id,emailId);
assert.equal((await admin.GET()).status,403);
const oldSession=cookie;
const known=await post({action:'forgot',email:'user@escola.example.test'}),resetToken=mailToken();
assert.deepEqual((await post({action:'forgot',email:'unknown@example.test'})).body,known.body);
assert.equal((await post({action:'reset',token:resetToken,password:'short'})).status,400);
const newPassword='updated-password-2026';
assert.equal((await post({action:'reset',token:resetToken,password:newPassword})).status,200);
assert.equal((await post({action:'reset',token:resetToken,password:newPassword})).status,400);
globalThis.testHeaders.set('cookie',oldSession);assert.equal(await auth.getCurrentUser(),null);
assert.equal((await post({action:'login',role:'student',login:emailId,password})).status,401);
assert.equal((await post({action:'login',role:'student',login:emailId,password:newPassword})).status,200);
const uid=sql.prepare('SELECT user_id FROM accounts WHERE login_id=?').get(emailId).user_id;
await assert.rejects(()=>auth.issueSession(uid,p.password_hash));
const count=messages.length;
assert.equal((await post({action:'setEmail',email:'changed@company.example.test',password})).status,401);assert.equal(messages.length,count);
assert.equal((await post({action:'setEmail',email:'changed@company.example.test',password:newPassword})).status,200);
const changeToken=mailToken();await post({action:'forgot',email:'user@escola.example.test'});const beforeChangeReset=mailToken();
assert.equal((await post({action:'verify',token:changeToken,password:newPassword})).status,200);
assert.equal((await post({action:'reset',token:beforeChangeReset,password})).status,400);
assert.equal((await post({action:'login',role:'student',login:'user@escola.example.test',password:newPassword})).status,401);
assert.equal((await post({action:'login',role:'student',login:'changed@company.example.test',password:newPassword})).status,200);
await post({action:'forgot',email:'changed@company.example.test'});const expired=mailToken();sql.prepare('UPDATE email_tokens SET expires=0 WHERE token_hash=?').run(await auth.digest(expired));
assert.equal((await post({action:'reset',token:expired,password})).status,400);
ip='192.0.2.11';await post({action:'login',role:'admin',login:'adm123',password});
assert.equal((await post({action:'setEmail',email:'admin@company.example.test',password})).status,200);
assert.equal((await post({action:'verify',token:mailToken(),password})).status,200);
await post({action:'forgot',email:'admin@company.example.test'});
assert.equal((await post({action:'reset',token:mailToken(),password:newPassword})).status,200);
assert.equal((await post({action:'login',role:'admin',login:'adm123',password})).status,401);
assert.equal((await post({action:'login',role:'admin',login:'admin@company.example.test',password:newPassword})).status,200);assert.equal((await admin.GET()).status,200);
const tokensBefore=sql.prepare('SELECT count(*) n FROM email_tokens').get().n;failMail=true;
assert.equal((await post({action:'setEmail',email:'failure@example.test',password:newPassword})).status,503);assert.equal(sql.prepare('SELECT count(*) n FROM email_tokens').get().n,tokensBefore);
assert.equal((await post({action:'forgot',email:'bad@'})).status,400);
assert.equal((await post({action:'forgot',email:'user@escola.example.test'},'https://evil.test')).status,403);
console.log('PASS: verified email login, password reset, expiry/replay, session revocation, preserved approval, email changes, admin recovery and provider failure.');
console.log('PASS: real password derivation, unique IDs, automatic registration, admin isolation, student/teacher denial, CSRF, logout/revocation, expiry, legacy linking and login throttling.');
sql.close();rmSync(temp,{recursive:true,force:true});
