import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,readFileSync,writeFileSync,readdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import path from 'node:path';import ts from 'typescript';
const temp=mkdtempSync(path.join(tmpdir(),'tufi-auth-'));
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
globalThis.testEnv={ADMIN_PROFILE_ID:'owner',AUTH_PEPPER:'test-only-pepper-never-used-in-production'};
globalThis.testHeaders=new Headers();globalThis.legacyUser=null;
writeFileSync(path.join(temp,'server.mjs'),compile(readFileSync('lib/server.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.testEnv;")));
writeFileSync(path.join(temp,'auth.mjs'),compile(readFileSync('lib/auth.ts','utf8').replace("import {headers} from 'next/headers';","const headers=async()=>globalThis.testHeaders;").replace("import {env} from 'cloudflare:workers';","const env=globalThis.testEnv;").replace("from './server'","from './server.mjs'")));
const rewrite=s=>s.replace("import {getChatGPTUser} from '@/app/chatgpt-auth';","const getChatGPTUser=async()=>globalThis.legacyUser;").replace("from '@/lib/server'","from './server.mjs'").replace("from '@/lib/auth'","from './auth.mjs'");
writeFileSync(path.join(temp,'route.mjs'),compile(rewrite(readFileSync('app/api/auth/route.ts','utf8'))));
writeFileSync(path.join(temp,'admin.mjs'),compile(rewrite(readFileSync('app/api/admin/route.ts','utf8'))));
const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+file,'utf8'));
globalThis.testDB={async batch(statements){sql.exec('BEGIN');try{const out=[];for(const stmt of statements)out.push(await stmt.execute());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}},prepare(query){let args=[];const stmt=sql.prepare(query);return {async execute(){if(/^SELECT/i.test(query))return {results:stmt.all(...args),meta:{changes:0}};const r=stmt.run(...args);return {results:[],meta:{changes:Number(r.changes)}}},bind(...a){args=a;return this},async first(){return stmt.get(...args)||null},async all(){return {results:stmt.all(...args)}},async run(){const r=stmt.run(...args);return {meta:{changes:Number(r.changes)}}}}}};

globalThis.testEnv.DB=globalThis.testDB;
const auth=await import('file://'+path.join(temp,'auth.mjs'));
const route=await import('file://'+path.join(temp,'route.mjs'));
const admin=await import('file://'+path.join(temp,'admin.mjs'));
const password='fixture-password-2026';
globalThis.testEnv.ADMIN_PASSWORD_HASH=await auth.hashPassword(password);
let cookie='',ip='192.0.2.1';
const post=async(body,origin='https://tufi.test')=>{const h=new Headers({'origin':origin,'cf-connecting-ip':ip,'cookie':cookie});globalThis.testHeaders=h;const r=await route.POST(new Request('https://tufi.test/api/auth',{method:'POST',headers:h,body:JSON.stringify(body)}));const set=r.headers.get('set-cookie');if(set){assert.match(set,/HttpOnly; Secure; SameSite=Lax/);cookie=set.split(';')[0];globalThis.testHeaders.set('cookie',cookie)}return {status:r.status,body:await r.json(),set}};
assert.equal((await route.GET()).status,200);assert.equal((await (await route.GET()).json()).account,null);
assert.equal((await post({action:'register',role:'admin',name:'Intruder',password})).status,400);
assert.equal((await post({action:'register',role:'student',name:'Alice',password},'https://evil.test')).status,403);
const registered=await post({action:'register',role:'student',name:'Alice',password,email:'owner@example.test',status:'approved'});
assert.equal(registered.status,201);assert.equal(registered.body.account.status,'pending');assert.match(registered.body.account.id,/^TF-[A-F0-9]{16}$/);
const studentId=registered.body.account.id,studentCookie=cookie;
const p=sql.prepare('SELECT p.*,a.password_hash FROM profiles p JOIN accounts a ON a.user_id=p.id WHERE a.login_id=?').get(studentId);
assert.equal(p.email,'');assert.equal(p.role,'student');assert.notEqual(p.password_hash,password);assert.equal(await auth.verifyPassword(password,p.password_hash),true);assert.equal(await auth.verifyPassword('wrong-password',p.password_hash),false);
assert.equal((await admin.GET()).status,403);
await post({action:'logout'});globalThis.testHeaders.set('cookie',studentCookie);assert.equal(await auth.getCurrentUser(),null);
assert.equal((await post({action:'login',role:'admin',login:studentId,password})).status,403);
assert.equal((await post({action:'login',role:'student',login:studentId,password:'wrong-password'})).status,401);
const waiting=await post({action:'login',role:'student',login:studentId,password});assert.equal(waiting.body.account.status,'pending');
await post({action:'logout'});
const owner=await post({action:'login',role:'admin',login:'adm123',password});assert.equal(owner.status,200);assert.equal(owner.body.account.role,'admin');assert.equal(owner.body.account.id,'ADM-0001');
const ownerCookie=cookie;assert.equal((await admin.GET()).status,200);
const approval=await admin.POST(new Request('https://tufi.test/api/admin',{method:'POST',headers:{origin:'https://tufi.test'},body:JSON.stringify({action:'user',id:p.id,role:'student',status:'approved',revision:0})}));assert.equal(approval.status,200);
const approved=await post({action:'login',role:'student',login:studentId.toLowerCase(),password});assert.equal(approved.body.account.status,'approved');assert.equal((await admin.GET()).status,403);
sql.prepare("UPDATE profiles SET status='blocked' WHERE id=?").run(p.id);assert.equal((await post({action:'login',role:'student',login:studentId,password})).status,403);
const teacher=await post({action:'register',role:'teacher',name:'Teacher',password});assert.equal(teacher.body.account.role,'teacher');assert.notEqual(teacher.body.account.id,studentId);assert.equal((await admin.GET()).status,403);
sql.prepare("UPDATE profiles SET role='teacher',status='approved' WHERE id=(SELECT user_id FROM accounts WHERE login_id=?)").run(teacher.body.account.id);assert.equal((await admin.GET()).status,403);
assert.equal((await post({action:'login',role:'admin',login:teacher.body.account.id,password})).status,403);
sql.prepare('UPDATE sessions SET expires=0').run();assert.equal(await auth.getCurrentUser(),null);
assert.equal((await post({action:'link',role:'student',name:'Legacy',password})).status,401);
sql.prepare("INSERT INTO profiles(id,name,email,status) VALUES('legacy','Old','verified@example.test','approved')").run();globalThis.legacyUser={userId:'legacy',email:'verified@example.test'};
const linked=await post({action:'link',role:'teacher',name:'Ignored',password});assert.equal(linked.status,201);assert.equal(linked.body.account.role,'student');assert.equal(linked.body.account.status,'approved');assert.equal(linked.body.account.name,'Old');assert.equal((await post({action:'link',role:'student',name:'Legacy',password})).status,409);
ip='192.0.2.2';for(let i=0;i<12;i++)assert.equal((await post({action:'login',role:'student',login:'TF-UNKNOWN',password})).status,401);assert.equal((await post({action:'login',role:'student',login:'TF-UNKNOWN',password})).status,429);
console.log('PASS: real password derivation, unique IDs, pending registration, admin-only approval, student/teacher denial, CSRF, logout/revocation, expiry, legacy linking and login throttling.');
sql.close();rmSync(temp,{recursive:true,force:true});
