'use client';
import {useEffect,useState} from 'react';
import {Compass,GraduationCap,ShieldCheck,UserRound,ArrowRight,Copy,LogOut,CheckCircle2,Clock3} from 'lucide-react';
import Game from './game';
import AccountEmail from './account-email';
type Role='student'|'teacher'|'admin';
type Account={id:string;name:string;role:Role;status:string;email?:string|null;emailVerified?:boolean};
const roles=[{id:'student' as Role,label:'Aluno',description:'Explore, aprenda e abra portais.',Icon:UserRound},{id:'teacher' as Role,label:'Professor',description:'Acompanhe sua turma e a evolução.',Icon:GraduationCap},{id:'admin' as Role,label:'Administrador',description:'Autorize contas e gerencie o jogo.',Icon:ShieldCheck}];
export async function authRequest(data?:unknown){const r=await fetch('/api/auth',{method:data?'POST':'GET',credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível entrar.');return d}
export default function Access({adminEntry=false}:{adminEntry?:boolean}){
 const [role,setRole]=useState<Role|null>(adminEntry?'admin':null),[tab,setTab]=useState<'login'|'register'|'link'>('login');
 const [account,setAccount]=useState<Account|null>(null),[entered,setEntered]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [name,setName]=useState(''),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[email,setEmail]=useState('');
 useEffect(()=>{authRequest().then(d=>setAccount(d.account)).catch(e=>setError(e.message)).finally(()=>setLoading(false));if(new URLSearchParams(location.search).get('migrate')==='1'){setRole('student');setTab('link')}},[]);
 async function logout(){setBusy(true);try{await authRequest({action:'logout'});setAccount(null);setEntered(false);setPassword('');setConfirm('');setNotice('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setError('');setNotice('');if(tab!=='login'&&password!==confirm){setError('As senhas precisam ser iguais.');return}setBusy(true);try{const d=await authRequest({action:tab,role,login,name,password,email});setAccount(d.account);setRole(d.account.role);setPassword('');setConfirm('');if(d.account.status==='approved')setEntered(true);else setNotice((tab==='link'?'Conta vinculada. Seu histórico foi preservado.':'Cadastro criado! Guarde seu ID para entrar novamente.')+' '+(d.emailNotice||''))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function refresh(){setBusy(true);setError('');try{const d=await authRequest();setAccount(d.account);setNotice(d.account?.status==='approved'?'Seu acesso está liberado!':'Sua solicitação ainda aguarda análise.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(account!.id);setNotice('ID copiado. Guarde-o para o próximo login.')}catch{setNotice('Selecione e copie o ID mostrado abaixo.')}}
 if(entered&&account?.status==='approved')return <Game initialView={account.role==='admin'?'admin':account.role==='teacher'?'teacher':'map'} accountId={account.id} accountEmail={account.email} onLogout={logout}/>;
 const selected=roles.find(r=>r.id===role);
 return <main className="access-shell"><section className="access-story"><a href="/" className="brand"><span className="brand-icon"><Compass/></span><span>TUFI<small>O ENIGMA DOS NÚMEROS</small></span></a><div className="access-story-copy"><p className="eyebrow">CADA DESCOBERTA ABRE UM CAMINHO</p><h1>Sua próxima aventura começa aqui.</h1><p>Seis regiões. Grandes descobertas.<br/>A matemática é a chave de cada portal.</p><div className="access-story-tags"><span>✦ Aprenda no seu ritmo</span><span>✧ Conquiste novos mundos</span></div></div><p className="access-footnote">Tufi · Uma jornada de matemática para o 6º ano</p></section>
 <section className="access-main" aria-label="Acesso ao jogo"><div className="access-content"><p className="eyebrow">BEM-VINDO AO MUNDO DE TUFI</p><h2>Como você quer entrar?</h2><p className="muted">Selecione o tipo da sua conta para continuar.</p><div className="role-options" aria-label="Tipo de conta">{roles.map(({id,label,description,Icon})=><button type="button" aria-pressed={role===id} className={'role-option '+(role===id?'selected':'')} key={id} disabled={busy} onClick={()=>{setRole(id);setTab('login');setPassword('');setConfirm('');setError('');setNotice('')}}><Icon size={25}/><strong>{label}</strong><small>{description}</small></button>)}</div>
 {error&&<p className="access-alert error" role="alert">{error}</p>}{notice&&<p className="access-alert" role="status">{notice}</p>}
 {loading?<p role="status">Verificando acesso…</p>:account&&(!role||account.role===role)?<div className="access-account"><p className="eyebrow">SUA CONTA · {roles.find(r=>r.id===account.role)?.label}</p><h3>Olá, {account.name}!</h3><label htmlFor="account-id">Seu ID de identificação e login</label><div className="account-id"><input id="account-id" readOnly value={account.id}/><button onClick={copy} aria-label="Copiar ID"><Copy size={18}/></button></div>{account.status==='approved'?<><p className="access-status"><CheckCircle2 size={19}/>Acesso autorizado</p><button className="primary full" onClick={()=>{setRole(account.role);setEntered(true)}}>Abrir {account.role==='admin'?'painel do administrador':account.role==='teacher'?'painel do professor':'aventura'}<ArrowRight size={18}/></button></>:<><p className="access-status"><Clock3 size={20}/>{account.status==='blocked'?'Conta bloqueada':'Aguardando autorização do administrador'}</p><p>{account.status==='blocked'?'Fale com o administrador para revisar seu acesso.':'Seu cadastro foi enviado. Quando o administrador aprovar, você poderá acessar sua área com este ID e a senha criada.'}</p><button className="secondary full" disabled={busy} onClick={refresh}>Verificar aprovação</button></>}<AccountEmail currentEmail={account.email}/><button className="access-logout" onClick={logout} disabled={busy}><LogOut size={16}/>Sair desta conta</button></div>:role?<div className="access-form-wrap"><h3>{selected?.label}</h3>{role!=='admin'&&<div className="access-tabs"><button type="button" className={tab==='login'?'selected':''} onClick={()=>{setTab('login');setError('')}}>Entrar</button><button type="button" className={tab==='register'?'selected':''} onClick={()=>{setTab('register');setError('')}}>Cadastro</button></div>}{account&&<p className="access-alert">Há uma conta de {roles.find(r=>r.id===account.role)?.label.toLowerCase()} conectada. Entre com outra conta ou <button onClick={logout}>saia dela</button>.</p>}
 <form className="form" onSubmit={submit}>{tab==='link'&&<p>Crie uma senha para sua conta antiga. Seu histórico e sua autorização serão mantidos.</p>}{tab==='login'?<><label htmlFor="login-id">{role==='admin'?'Usuário, ID ou e-mail confirmado':'ID ou e-mail confirmado'}</label><input id="login-id" name="username" autoComplete="username" value={login} onChange={e=>setLogin(e.target.value)} placeholder={role==='admin'?'Seu login de administrador':'TF-… ou seu e-mail'} maxLength={254} required/></>:<><label htmlFor="signup-name">Nome ou apelido</label><input id="signup-name" autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={40} required placeholder="Como quer ser chamado?"/></>}
 <>{tab!=='login'&&<><label htmlFor="signup-email">E-mail (recomendado)</label><input id="signup-email" type="email" autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/><p className="support left">Prefira o e-mail da rede estadual, escola ou empresa. E-mails pessoais também são aceitos. Confirme o endereço recebido por e-mail para habilitar login e recuperação.</p></>}</><label htmlFor="login-password">Senha</label><input id="login-password" name="password" type="password" autoComplete={tab==='login'?'current-password':'new-password'} minLength={10} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required placeholder={tab==='login'?'Digite sua senha':'Pelo menos 10 caracteres'}/>{tab!=='login'&&<><label htmlFor="confirm-password">Confirmar senha</label><input id="confirm-password" type="password" autoComplete="new-password" minLength={10} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)} required/><p className="support left">Seu ID será gerado e o acesso ficará disponível imediatamente.</p></>}<button className="primary full" disabled={busy}>{busy?'Aguarde…':tab==='login'?'Entrar':tab==='link'?'Vincular conta anterior':'Criar conta'}<ArrowRight size={18}/></button></form>{tab==='login'&&<a className="forgot-link" href="/conta">Esqueci minha senha</a>}{role==='admin'?<p className="support left">Acesso exclusivo do administrador. Não há cadastro público para este perfil.</p>:<p className="support left">Já usava o jogo com ChatGPT? <a href="/signin-with-chatgpt?return_to=%2F%3Fmigrate%3D1" target="_top">Vincular minha conta anterior</a></p>}</div>:<p className="access-prompt">↑ Escolha Aluno, Professor ou Administrador.</p>}
 <div className="access-bottom"><a href="/offline.html">Treino offline</a><span>Seu progresso online fica vinculado à sua conta.</span></div></div></section></main>
}
