'use client';
import {useState,useEffect,useCallback} from 'react';
import {Users,ShieldCheck,GraduationCap,RefreshCw,Search,Plus,Settings2,KeyRound,Trash2,Copy} from 'lucide-react';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const statuses:Record<string,string>={pending:'Pendente',approved:'Aprovado',blocked:'Bloqueado'};
const roles:Record<string,string>={student:'Aluno',teacher:'Professor'};
async function request(body?:any){const r=await fetch('/api/admin',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível completar a ação.');return d}
export default function AdminPanel({onHistory}:{onHistory:(id:string,name:string)=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[edit,setEdit]=useState<any>(null),[group,setGroup]=useState<any>(null),[accountAction,setAccountAction]=useState<any>(null),[temporary,setTemporary]=useState('');
 const load=useCallback(async()=>{try{setData(await request())}catch(e:any){setError(e.message)}},[]);useEffect(()=>{load()},[load]);
 const save=async(body:any)=>{setBusy(true);setError('');setNotice('');try{await request(body);await load();setEdit(null);setGroup(null);setNotice('Alteração salva e registrada.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const manageAccount=async(body:any)=>{setBusy(true);setError('');setNotice('');try{const result=await request(body);if(result.temporary){setTemporary(result.temporary);setNotice('Senha redefinida. Copie a senha temporária antes de fechar esta janela.')}else{setAccountAction(null);setNotice('Perfil e dados da conta excluídos.')}await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const users=data?.users||[],classes=data?.classes||[],filtered=users.filter((u:any)=>(filter==='all'||u.status===filter)&&`${u.name} ${u.email} ${u.login_id||u.id}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="admin-panel"><div className="page-title"><div><p className="eyebrow">CONTROLE DO JOGO</p><h1>Administração</h1><p>Gerencie contas, turmas e resultados do jogo.</p></div><button className="secondary" onClick={load} disabled={busy}><RefreshCw size={17}/>Atualizar</button></div>
 {error&&<div className="message error" role="alert">{error}</div>}{notice&&<div className="message" role="status">{notice}</div>}
 <div className="admin-stats">{[[Users,'Contas cadastradas',users.filter((u:any)=>u.id!==data?.ownerId).length],[Users,'Alunos',users.filter((u:any)=>u.id!==data?.ownerId&&u.role==='student'&&u.status==='approved').length],[GraduationCap,'Professores',users.filter((u:any)=>u.id!==data?.ownerId&&u.role==='teacher'&&u.status==='approved').length],[ShieldCheck,'Turmas',classes.length]].map(([Icon,label,count]:any)=><div className="panel" key={label}><Icon size={22}/><strong>{count}</strong><span>{label}</span></div>)}</div>
 <div className="panel"><h2>Professores e alunos</h2><div className="filters"><label className="admin-search"><Search size={18}/><input aria-label="Buscar por nome ou e-mail" placeholder="Buscar nome ou e-mail" value={search} onChange={e=>setSearch(e.target.value)}/></label><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filtrar situação"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os cadastros</SelectItem>{Object.entries(statuses).map(([k,v])=><SelectItem value={k} key={k}>{v}</SelectItem>)}</SelectContent></Select></div>
 <Table><TableHeader><TableRow><TableHead>Conta e login</TableHead><TableHead>Papel</TableHead><TableHead>Situação</TableHead><TableHead>Turma</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{filtered.map((u:any)=><TableRow key={u.id}><TableCell><strong>{u.name}</strong><small className="admin-sub">Login: {u.id===data.ownerId?'ADM-0001':u.login_id||u.id}</small><small className="admin-sub">E-mail: {u.account_email||'Não confirmado'}</small></TableCell><TableCell>{u.id===data.ownerId?'Administrador':roles[u.role]}</TableCell><TableCell><span className={'status '+u.status}>{u.id===data.ownerId?'Proprietário':statuses[u.status]}</span>{u.session_expires>Date.now()&&<small className="admin-sub">Sessão ativa</small>}</TableCell><TableCell>{u.class_name||'Sem turma'}</TableCell><TableCell><div className="actions compact">{u.id!==data.ownerId&&<><button className="secondary" onClick={()=>setEdit({...u,role:u.role})}><Settings2 size={16}/>Gerenciar</button><button className="secondary" onClick={()=>{setTemporary('');setAccountAction({...u,type:'reset'})}}><KeyRound size={16}/>Redefinir senha</button><button className="danger" onClick={()=>{setTemporary('');setAccountAction({...u,type:'delete'})}}><Trash2 size={16}/>Excluir</button></>}<button className="secondary" onClick={()=>onHistory(u.id,u.name)}>Histórico</button></div></TableCell></TableRow>)}</TableBody></Table>{!data&&<p>Carregando cadastros…</p>}{data&&!filtered.length&&<p>Nenhuma conta encontrada.</p>}</div>
 <div className="panel"><div className="admin-heading"><h2>Turmas</h2><button className="primary" onClick={()=>setGroup({name:'',teacher:data?.ownerId||''})}><Plus size={17}/>Nova turma</button></div><div className="class-list">{classes.map((c:any)=><article className="panel" key={c.id}><h3>{c.name}</h3><p>{c.teacher_name||'Professor sem perfil'} · {c.students} alunos</p><p>Código: <strong>{c.code}</strong></p><div className="actions"><button className="secondary" onClick={()=>setGroup({...c})}>Editar turma</button><button className="secondary" disabled={busy} onClick={()=>setGroup({...c,rotate:true})}>Trocar código</button></div></article>)}</div>{!classes.length&&<p>Crie uma turma e selecione um professor aprovado para acompanhá-la.</p>}</div>
 <div className="panel"><h2>Registro das alterações</h2><p>Últimas 100 alterações administrativas.</p><Table><TableHeader><TableRow><TableHead>Quando</TableHead><TableHead>Ação</TableHead><TableHead>Cadastro ou turma</TableHead><TableHead>Detalhes</TableHead></TableRow></TableHeader><TableBody>{(data?.audit||[]).map((a:any)=>{const d=JSON.parse(a.details);const labels:Record<string,string>={user:'Cadastro atualizado',class:'Turma atualizada',rotateCode:'Código trocado',resetPassword:'Senha redefinida',deleteUser:'Perfil excluído'};return <TableRow key={a.id}><TableCell>{new Date(a.created).toLocaleString('pt-BR')}</TableCell><TableCell>{labels[a.action]||a.action}</TableCell><TableCell>{a.target_name||d.name||classes.find((c:any)=>c.id===a.target)?.name||'Registro'}</TableCell><TableCell>{d.after?`${roles[d.after.role]} · ${statuses[d.after.status]}`:d.loginId?`Login: ${d.loginId}`:d.name||'Código anterior invalidado'}</TableCell></TableRow>})}</TableBody></Table></div>
 <p className="support left">Novas contas entram automaticamente. Você ainda pode bloquear uma conta, trocar seu papel, redefinir sua senha ou excluí-la.</p>
 <Dialog open={!!edit} onOpenChange={open=>{if(!open&&!busy)setEdit(null)}}><DialogContent><DialogHeader><DialogTitle>Gerenciar {edit?.name}</DialogTitle><DialogDescription>Defina o papel, a autorização e a turma. Bloquear interrompe o acesso online sem apagar o histórico.</DialogDescription></DialogHeader>{edit&&<form className="form" onSubmit={e=>{e.preventDefault();save({action:'user',id:edit.id,role:edit.role,status:edit.status,classId:edit.class_id,revision:edit.revision})}}><label>Papel</label><Select value={edit.role} onValueChange={v=>setEdit({...edit,role:v})}><SelectTrigger aria-label="Papel"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(roles).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><label>Situação</label><Select value={edit.status} onValueChange={v=>setEdit({...edit,status:v})}><SelectTrigger aria-label="Situação"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(statuses).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><label>Turma do aluno</label><Select value={edit.class_id||'none'} onValueChange={v=>setEdit({...edit,class_id:v==='none'?null:v})}><SelectTrigger aria-label="Turma do aluno"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sem turma</SelectItem>{classes.map((c:any)=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select>{error&&<p role="alert" className="orange">{error}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar autorização'}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!group} onOpenChange={open=>{if(!open&&!busy)setGroup(null)}}><DialogContent><DialogHeader><DialogTitle>{group?.rotate?'Trocar código de entrada':group?.id?'Editar turma':'Criar turma'}</DialogTitle><DialogDescription>{group?.rotate?'O código anterior deixará de funcionar. Os alunos vinculados permanecem na turma.':'Escolha o nome e o professor responsável.'}</DialogDescription></DialogHeader>{group&&<form className="form" onSubmit={e=>{e.preventDefault();save(group.rotate?{action:'rotateCode',id:group.id}:{action:'class',id:group.id,name:group.name,teacher:group.teacher})}}>{!group.rotate&&<><label htmlFor="admin-class">Nome</label><input id="admin-class" required minLength={2} maxLength={40} value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/><label>Responsável</label><Select value={group.teacher} onValueChange={v=>setGroup({...group,teacher:v})}><SelectTrigger aria-label="Professor responsável"><SelectValue/></SelectTrigger><SelectContent>{users.filter((u:any)=>u.id===data.ownerId||u.id!==data?.ownerId&&u.role==='teacher'&&u.status==='approved').map((u:any)=><SelectItem key={u.id} value={u.id}>{u.name}{u.id===data.ownerId?' (administrador)':''}</SelectItem>)}</SelectContent></Select></>}{error&&<p role="alert" className="orange">{error}</p>}<button className="primary" disabled={busy}>{group.rotate?'Confirmar troca':'Salvar turma'}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!accountAction} onOpenChange={open=>{if(!open&&!busy){setAccountAction(null);setTemporary('')}}}><DialogContent><DialogHeader><DialogTitle>{accountAction?.type==='delete'?'Excluir perfil':'Redefinir senha'} de {accountAction?.name}</DialogTitle><DialogDescription>{accountAction?.type==='delete'?'Esta ação exclui a conta, as sessões, o progresso e o histórico de partidas. Ela não pode ser desfeita.':'A senha atual não pode ser visualizada. Uma nova senha temporária será criada e todas as sessões antigas serão encerradas.'}</DialogDescription></DialogHeader>{temporary?<div className="form"><label htmlFor="temporary-password">Senha temporária</label><div className="account-id"><input id="temporary-password" readOnly value={temporary}/><button type="button" onClick={()=>navigator.clipboard.writeText(temporary)} aria-label="Copiar senha temporária"><Copy size={18}/></button></div><p className="support left">Entregue esta senha ao titular da conta por um canal seguro. Ela só aparece nesta janela.</p><button className="primary" onClick={()=>{setAccountAction(null);setTemporary('')}}>Concluir</button></div>:accountAction&&<div className="form">{error&&<p role="alert" className="orange">{error}</p>}<button className={accountAction.type==='delete'?'danger full':'primary full'} disabled={busy} onClick={()=>manageAccount({action:accountAction.type==='delete'?'deleteUser':'resetPassword',id:accountAction.id})}>{busy?'Aguarde…':accountAction.type==='delete'?'Excluir perfil definitivamente':'Criar senha temporária'}</button><button className="secondary full" disabled={busy} onClick={()=>setAccountAction(null)}>Cancelar</button></div>}</DialogContent></Dialog>
 </section>
}
