'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Lock,Check,Compass,Play,Volume2,VolumeX,X} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {regions} from '@/lib/content';
import {useTufiOutfit} from './appearance';
import {journey,achievements,chapters,lessons,worldStories} from '@/lib/adventure';
export function SecretDiscovery({stats,onExplore}:{stats:any[];onExplore:()=>void}){
 const j=journey(stats);
 if(j.baseMastered<5)return null;
 const complete=j.best[6]>=400;
 return <section className={'secret-signal '+(j.expansionUnlocked?'revealed':'locked-signal')} aria-label={j.expansionUnlocked?'Portal do sétimo mundo':'Indícios do novo mundo'}>
  <span className="secret-rune" aria-hidden="true">{j.expansionUnlocked?'✦':'?'}</span>
  <div><p className="eyebrow">{j.expansionUnlocked?'O SÉTIMO SINAL':'UM SINAL DESCONHECIDO'}</p>
   <h2>{j.expansionUnlocked?complete?'Você dominou o Reino da Divisibilidade!':'Novo mundo desbloqueado: Reino da Divisibilidade':'Há uma passagem escondida na Fortaleza'}</h2>
   <p>{j.expansionUnlocked?complete?'Os sete portais estão abertos. Sua jornada está completa!':'Os seis cristais revelaram um novo portal no mapa. Tufi está pronto para guiar você pelos múltiplos, divisores e números primos.':'Um símbolo desconhecido surgiu entre os seis selos. Complete os requisitos para descobrir de onde vem essa energia.'}</p>
   {j.expansionUnlocked?<button className="primary" onClick={onExplore}>{complete?'Revisitar o sétimo mundo':'Entrar no novo mundo'}</button>:<ul>
    <li>{j.baseMastered===6?'✓':'○'} Abra os seis portais: {j.baseMastered}/6</li>
    <li>{j.baseXp>=2600?'✓':'○'} Alcance 2.600 XP nos seis mundos: {j.baseXp}/2600</li>
    <li>{j.fortressCorrect>=5?'✓':'○'} Acerte cinco enigmas na Fortaleza: {Math.min(j.fortressCorrect,5)}/5</li>
   </ul>}
  </div>
 </section>
}
export function TufiGuide({children}:{children:React.ReactNode}){const outfit=useTufiOutfit();return <aside className="tufi-guide"><img className="guide-mascot" src={outfit.image} alt=""/><div><strong>Tufi · seu guia</strong><p>{children}</p></div></aside>}
export function WorldStory({region,onClose,onStart,busy=false}:{region:number;onClose:()=>void;onStart:()=>void;busy?:boolean}){
 const outfit=useTufiOutfit();
 const story=worldStories[region]||worldStories[0],[speaking,setSpeaking]=useState(false),[speechAvailable,setSpeechAvailable]=useState(false),titleRef=useRef<HTMLHeadingElement>(null),dialogRef=useRef<HTMLElement>(null),closeRef=useRef(onClose);
 useEffect(()=>{closeRef.current=onClose},[onClose]);
 useEffect(()=>{const previous=document.body.style.overflow,timer=window.setTimeout(()=>setSpeechAvailable('speechSynthesis'in window&&'SpeechSynthesisUtterance'in window),0);document.body.style.overflow='hidden';titleRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){closeRef.current();return}if(event.key!=='Tab')return;const controls=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],[tabindex]:not([tabindex="-1"])')||[]);if(!controls.length)return;const first=controls[0],last=controls.at(-1)!;if(event.shiftKey&&(document.activeElement===first||!controls.includes(document.activeElement as HTMLElement))){event.preventDefault();last.focus()}else if(!event.shiftKey&&(document.activeElement===last||!controls.includes(document.activeElement as HTMLElement))){event.preventDefault();first.focus()}};window.addEventListener('keydown',key);return()=>{window.clearTimeout(timer);window.removeEventListener('keydown',key);window.speechSynthesis?.cancel();document.body.style.overflow=previous}},[]);
 const stop=()=>{window.speechSynthesis?.cancel();setSpeaking(false)};
 const speak=()=>{if(!speechAvailable)return;if(speaking){stop();return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(`Olá, explorador! Eu sou o Tufi. ${story.subtitle}. ${story.title}. ${story.lines.join(' ')}`);utterance.lang='pt-BR';utterance.rate=.9;utterance.pitch=1.05;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>setSpeaking(false);setSpeaking(true);window.speechSynthesis.speak(utterance)};
 const close=()=>{stop();onClose()};
 const start=()=>{stop();onStart()};
 return <div className="story-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section ref={dialogRef} className="story-dialog" role="dialog" aria-modal="true" aria-labelledby="world-story-title" aria-describedby="world-story-description"><button className="story-close" onClick={close} aria-label="Fechar história"><X/></button><div className="story-visual" aria-hidden="true"><span className="story-orbit orbit-one">÷</span><span className="story-orbit orbit-two">△</span><span className="story-orbit orbit-three">7</span><img src={outfit.image} alt=""/></div><div className="story-copy"><p className="eyebrow">Tufi conta a história · Região {String(region+1).padStart(2,'0')}</p><span className="story-region">{story.subtitle}</span><h1 id="world-story-title" ref={titleRef} tabIndex={-1}>{story.title}</h1><div id="world-story-description" className="story-pages">{story.lines.map((line,index)=><p key={line}><span aria-hidden="true">{index+1}</span>{line}</p>)}</div><div className="story-narrator"><img src={outfit.image} alt="Tufi, guia da aventura, segurando um compasso matemático dourado"/><div><strong>Tufi · seu guia</strong><span aria-live="polite">{speaking?'Estou contando esta história...':'Quer ouvir a história em voz alta?'}</span></div>{speechAvailable&&<button className="secondary" onClick={speak} aria-pressed={speaking}>{speaking?<VolumeX size={19}/>:<Volume2 size={19}/>} {speaking?'Parar narração':'Ouvir Tufi'}</button>}</div><div className="story-actions"><button className="secondary" onClick={close}>Agora não</button><button className="primary" onClick={start} disabled={busy}><Play size={19} fill="currentColor"/>{busy?'Preparando missão...':'Começar missão'}</button></div></div></section></div>
}
export function JourneyPanel({stats,active,onSelect}:{stats:any[];active:any;onSelect:(i:number)=>void}){const j=journey(stats),discover=j.expansionUnlocked&&j.best[6]<400,complete=j.expansionUnlocked&&j.mastered===7,current=discover||complete?6:active?.region??j.next,resuming=!discover&&!complete&&!!active&&current===active.region,total=j.expansionUnlocked?7:6;return <section className="journey-panel"><div><span className="eyebrow">SUA JORNADA</span><h2>{resuming?`Em andamento: ${regions[current].name}`:discover?'O Sétimo Sinal foi revelado':complete?'Você completou os sete mundos':`Próxima região: ${regions[current].name}`}</h2><p>{resuming?`Desafio ${active.step+1} de 5. Continue de onde parou.`:discover?'Os seis cristais abriram uma passagem que não existia no mapa.':complete?'Todos os portais estão abertos. Você pode revisitar os mundos e continuar praticando.':j.baseMastered===6?'Todos os portais conhecidos estão abertos. Algo ainda parece incompleto...':'Conquiste 4 cristais em uma missão para abrir o próximo portal.'}</p><button className="secondary" onClick={()=>onSelect(current)}>{discover?'Investigar o portal secreto':complete?'Revisitar o sétimo mundo':'Ver minha próxima missão'}</button></div><div className="journey-meter"><strong>{j.percent}%</strong><span>{j.mastered} de {total} portais abertos · {j.crystals}/{total*5} cristais</span><Progress value={j.percent} aria-label={`${j.percent}% da jornada, ${j.mastered} portais abertos`}/></div></section>}
export function MissionTrail({region,best,active,finished}:{region:number;best:number;active:any;finished:boolean}){const step=active?.region===region?active.step:0;return <ol className="mission-trail">{chapters[region].map((name,i)=><li key={name}><span>{step>=Math.min(5,(i+1)*2)||finished?<Check size={17}/>:i+1}</span><div><strong>{name}</strong><small>{i===2?'Guardião · desafio 5':`Missão ${i+1} · desafios ${i*2+1} e ${i*2+2}`}</small></div></li>)}<li><span>{best>=400?<Check size={17}/>:<Lock size={17}/>}</span><div><strong>Portal da região</strong><small>{best>=400?'Aberto!':`Faltam ${Math.max(0,4-best/100)} acertos no melhor resultado para abrir.`}</small></div></li></ol>}
export function Achievements({stats}:{stats:any[]}){return <section><div className="page-title"><div><p className="eyebrow">SUAS DESCOBERTAS</p><h1>Conquistas da aventura</h1><p>Cada medalha registra algo que você aprendeu ou explorou.</p></div></div><div className="badge-grid">{achievements(stats).filter(a=>a.id!=='seventh-signal'||a.earned).map(a=><article key={a.id} className={'panel badge '+(a.earned?'earned':'')}><span className="badge-symbol" aria-hidden="true">{a.symbol}</span><h2>{a.name}</h2><p>{a.description}</p><strong>{a.earned?'✓ Conquistada':`${Math.min(a.value,a.goal)} de ${a.goal}`}</strong><Progress value={Math.min(100,a.value/a.goal*100)} aria-label={`${a.name}: ${Math.min(a.value,a.goal)} de ${a.goal}`}/></article>)}</div></section>}
export function ExplorerBook({stats}:{stats:any[]}){const j=journey(stats),visibleLessons=j.expansionUnlocked?lessons:lessons.slice(0,6),[topic,setTopic]=useState(0),[answer,setAnswer]=useState<number|null>(null);const l=visibleLessons[topic]||visibleLessons[0],open=j.unlocked[topic];return <section><div className="page-title"><div><p className="eyebrow">REVISAR TAMBÉM É EXPLORAR</p><h1>Meu Livro do Explorador</h1><p>Novas páginas ficam disponíveis quando você abre uma região.</p></div></div><div className="book-layout"><nav className="book-index" aria-label="Conteúdos do livro">{visibleLessons.map((l,i)=><button key={i} className={'secondary '+(topic===i?'book-selected':'')} aria-pressed={topic===i} onClick={()=>{setTopic(i);setAnswer(null)}}>{j.best[i]>=400?<Check size={18}/>:j.unlocked[i]?<BookOpen size={18}/>:<Lock size={18}/>}<span>{l.title}<small>{j.best[i]>=400?'Região dominada':j.unlocked[i]?'Disponível para revisar':'Página bloqueada'}</small></span></button>)}</nav><article className="panel book-page"><h2>{l.title}</h2>{!open?<TufiGuide>Abra o portal anterior para descobrir esta página. Você pode revisar as páginas já disponíveis enquanto isso.</TufiGuide>:<><p>{l.text}</p><div className="worked-example"><strong>Vamos ver um exemplo</strong><p>{l.example}</p></div><h3>Experimente: {l.question}</h3><div className="book-answers">{l.options.map((o,i)=><button className="secondary" key={i} onClick={()=>setAnswer(i)} aria-pressed={answer===i}>{o}</button>)}</div>{answer!==null&&<div className="feedback" role="status"><strong>{answer===l.answer?'✓ Você entendeu!':'Vamos pensar em outro caminho.'}</strong><p>{answer===l.answer?l.explanation:'Leia novamente o exemplo, observe a operação e tente outra resposta.'}</p></div>}<p className="support left">Atividade de revisão: sem cronômetro e sem alterar o ranking.</p></>}</article></div></section>}
export function TeacherInsights({data}:{data:any}){if(!data)return null;return <section className="teacher-insights"><div className="panel"><h2>Conteúdos para retomar</h2><p>Dados das últimas {data.sample||0} missões vinculadas, até 1.000. Sem respostas, não há diagnóstico.</p><div className="topic-grid">{(data.topics||[]).map((t:any)=><article key={t.region}><strong>{t.name}</strong><p>{t.answers?`${t.errors} erros em ${t.answers} respostas (${Math.round(t.errors/t.answers*100)}%)`:'Ainda sem respostas'}</p><Progress value={t.answers?t.errors/t.answers*100:0} aria-label={`${t.name}: ${t.errors} erros de ${t.answers}`}/><small>{!t.answers?'Aguardar prática':t.errors/t.answers>=.4?'Sugestão: retomar conceitos e exemplos.':t.errors?'Sugestão: revisar os erros pontuais.':'Acertos consistentes nesta amostra.'}</small></article>)}</div></div><div className="panel"><h2>Questões com mais erros</h2>{!data.questions?.length?<p>Ainda não há erros registrados nesta amostra.</p>:<Table><TableHeader><TableRow><TableHead>Questão</TableHead><TableHead>Conteúdo</TableHead><TableHead>Erros / respostas</TableHead></TableRow></TableHeader><TableBody>{data.questions.map((q:any,i:number)=><TableRow key={i}><TableCell className="wrap-cell">{q.text}</TableCell><TableCell>{regions[q.region].topic}</TableCell><TableCell>{q.errors}/{q.answers}</TableCell></TableRow>)}</TableBody></Table>}</div><div className="panel"><h2>Evolução da turma</h2><p>Até 14 dias com atividade da amostra, agrupados pela data UTC de início da missão.</p><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Respostas</TableHead><TableHead>Acertos</TableHead><TableHead>Aproveitamento</TableHead></TableRow></TableHeader><TableBody>{(data.evolution||[]).map((d:any)=><TableRow key={d.day}><TableCell>{d.day.split('-').reverse().join('/')}</TableCell><TableCell>{d.answers}</TableCell><TableCell>{d.correct}</TableCell><TableCell>{Math.round(d.correct/d.answers*100)}%</TableCell></TableRow>)}</TableBody></Table>{!data.evolution?.length&&<p>O acompanhamento aparecerá conforme os alunos jogarem.</p>}</div></section>}
