'use client';
import {useState} from 'react';
import {BookOpen,Lock,Check,Sparkles,Compass} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {regions} from '@/lib/content';
import {journey,achievements,chapters,lessons} from '@/lib/adventure';
export function TufiGuide({children}:{children:React.ReactNode}){return <aside className="tufi-guide"><span className="guide-emblem" aria-hidden="true"><Compass/></span><div><strong>Tufi · seu guia</strong><p>{children}</p></div></aside>}
export function JourneyPanel({stats,active,onSelect}:{stats:any[];active:any;onSelect:(i:number)=>void}){const j=journey(stats),current=active?.region??j.next;return <section className="journey-panel"><div><span className="eyebrow">SUA JORNADA</span><h2>{active?`Em andamento: ${regions[current].name}`:`Próxima região: ${regions[current].name}`}</h2><p>{active?`Desafio ${active.step+1} de 5. Continue de onde parou.`:j.mastered===6?'Todos os portais abertos! Revise e busque os 30 cristais.':'Conquiste 4 cristais em uma missão para abrir o próximo portal.'}</p><button className="secondary" onClick={()=>onSelect(current)}>Ver minha próxima missão</button></div><div className="journey-meter"><strong>{j.percent}%</strong><span>{j.mastered} de 6 portais abertos · {j.crystals}/30 cristais</span><Progress value={j.percent} aria-label={`${j.percent}% da jornada, ${j.mastered} portais abertos`}/></div></section>}
export function MissionTrail({region,best,active,finished}:{region:number;best:number;active:any;finished:boolean}){const step=active?.region===region?active.step:0;return <ol className="mission-trail">{chapters[region].map((name,i)=><li key={name}><span>{step>=Math.min(5,(i+1)*2)||finished?<Check size={17}/>:i+1}</span><div><strong>{name}</strong><small>{i===2?'Guardião · desafio 5':`Missão ${i+1} · desafios ${i*2+1} e ${i*2+2}`}</small></div></li>)}<li><span>{best>=400?<Check size={17}/>:<Lock size={17}/>}</span><div><strong>Portal da região</strong><small>{best>=400?'Aberto!':`Faltam ${Math.max(0,4-best/100)} acertos no melhor resultado para abrir.`}</small></div></li></ol>}
export function Achievements({stats}:{stats:any[]}){return <section><div className="page-title"><div><p className="eyebrow">SUAS DESCOBERTAS</p><h1>Conquistas da aventura</h1><p>Cada medalha registra algo que você aprendeu ou explorou.</p></div></div><div className="badge-grid">{achievements(stats).map(a=><article key={a.id} className={'panel badge '+(a.earned?'earned':'')}><span className="badge-symbol" aria-hidden="true">{a.symbol}</span><h2>{a.name}</h2><p>{a.description}</p><strong>{a.earned?'✓ Conquistada':`${Math.min(a.value,a.goal)} de ${a.goal}`}</strong><Progress value={Math.min(100,a.value/a.goal*100)} aria-label={`${a.name}: ${Math.min(a.value,a.goal)} de ${a.goal}`}/></article>)}</div></section>}
export function ExplorerBook({stats}:{stats:any[]}){const j=journey(stats),[topic,setTopic]=useState(0),[answer,setAnswer]=useState<number|null>(null);const l=lessons[topic],open=j.unlocked[topic];return <section><div className="page-title"><div><p className="eyebrow">REVISAR TAMBÉM É EXPLORAR</p><h1>Meu Livro do Explorador</h1><p>Novas páginas ficam disponíveis quando você abre uma região.</p></div></div><div className="book-layout"><nav className="book-index" aria-label="Conteúdos do livro">{lessons.map((l,i)=><button key={i} className={'secondary '+(topic===i?'book-selected':'')} aria-pressed={topic===i} onClick={()=>{setTopic(i);setAnswer(null)}}>{j.best[i]>=400?<Check size={18}/>:j.unlocked[i]?<BookOpen size={18}/>:<Lock size={18}/>}<span>{l.title}<small>{j.best[i]>=400?'Região dominada':j.unlocked[i]?'Disponível para revisar':'Página bloqueada'}</small></span></button>)}</nav><article className="panel book-page"><h2>{l.title}</h2>{!open?<TufiGuide>Abra o portal anterior para descobrir esta página. Você pode revisar as páginas já disponíveis enquanto isso.</TufiGuide>:<><p>{l.text}</p><div className="worked-example"><strong>Vamos ver um exemplo</strong><p>{l.example}</p></div><h3>Experimente: {l.question}</h3><div className="book-answers">{l.options.map((o,i)=><button className="secondary" key={i} onClick={()=>setAnswer(i)} aria-pressed={answer===i}>{o}</button>)}</div>{answer!==null&&<div className="feedback" role="status"><strong>{answer===l.answer?'✓ Você entendeu!':'Vamos pensar em outro caminho.'}</strong><p>{answer===l.answer?l.explanation:'Leia novamente o exemplo, observe a operação e tente outra resposta.'}</p></div>}<p className="support left">Atividade de revisão: sem cronômetro e sem alterar o ranking.</p></>}</article></div></section>}
export function TeacherInsights({data}:{data:any}){if(!data)return null;return <section className="teacher-insights"><div className="panel"><h2>Conteúdos para retomar</h2><p>Dados das últimas {data.sample||0} missões vinculadas, até 1.000. Sem respostas, não há diagnóstico.</p><div className="topic-grid">{(data.topics||[]).map((t:any)=><article key={t.region}><strong>{t.name}</strong><p>{t.answers?`${t.errors} erros em ${t.answers} respostas (${Math.round(t.errors/t.answers*100)}%)`:'Ainda sem respostas'}</p><Progress value={t.answers?t.errors/t.answers*100:0} aria-label={`${t.name}: ${t.errors} erros de ${t.answers}`}/><small>{!t.answers?'Aguardar prática':t.errors/t.answers>=.4?'Sugestão: retomar conceitos e exemplos.':t.errors?'Sugestão: revisar os erros pontuais.':'Acertos consistentes nesta amostra.'}</small></article>)}</div></div><div className="panel"><h2>Questões com mais erros</h2>{!data.questions?.length?<p>Ainda não há erros registrados nesta amostra.</p>:<Table><TableHeader><TableRow><TableHead>Questão</TableHead><TableHead>Conteúdo</TableHead><TableHead>Erros / respostas</TableHead></TableRow></TableHeader><TableBody>{data.questions.map((q:any,i:number)=><TableRow key={i}><TableCell className="wrap-cell">{q.text}</TableCell><TableCell>{regions[q.region].topic}</TableCell><TableCell>{q.errors}/{q.answers}</TableCell></TableRow>)}</TableBody></Table>}</div><div className="panel"><h2>Evolução da turma</h2><p>Até 14 dias com atividade da amostra, agrupados pela data UTC de início da missão.</p><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Respostas</TableHead><TableHead>Acertos</TableHead><TableHead>Aproveitamento</TableHead></TableRow></TableHeader><TableBody>{(data.evolution||[]).map((d:any)=><TableRow key={d.day}><TableCell>{d.day.split('-').reverse().join('/')}</TableCell><TableCell>{d.answers}</TableCell><TableCell>{d.correct}</TableCell><TableCell>{Math.round(d.correct/d.answers*100)}%</TableCell></TableRow>)}</TableBody></Table>{!data.evolution?.length&&<p>O acompanhamento aparecerá conforme os alunos jogarem.</p>}</div></section>}
