'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {Compass,Map,Backpack,Trophy,ChartNoAxesCombined,Settings,UserRound,GraduationCap,ChevronRight,ArrowLeft,Play,Star,Sparkles,Check,Lock,Volume2,Download,Printer,WifiOff,ShieldCheck,BookOpen,RotateCcw} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableBody,TableHead,TableHeader,TableRow,TableCell} from '@/components/ui/table';
import {regions,gears} from '@/lib/content';
type View='map'|'play'|'inventory'|'history'|'ranking'|'profile'|'settings'|'teacher';
async function api(action?:any,query=''){const r=await fetch('/api/game'+query,{method:action?'POST':'GET',headers:action?{'Content-Type':'application/json'}:undefined,body:action?JSON.stringify(action):undefined});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Tente novamente.');return d}
function exportCSV(rows:any[],name:string){const cell=(s:any)=>'"'+String(s??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export default function Game(){
 const [view,setView]=useState<View>('map'),[selected,setSelected]=useState(0),[me,setMe]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [run,setRun]=useState<any>(null),[active,setActive]=useState<any>(null),[feedback,setFeedback]=useState<any>(null),[choice,setChoice]=useState<number|null>(null),[history,setHistory]=useState<any[]>([]),[ranking,setRanking]=useState<any[]>([]),[rankMode,setRankMode]=useState('score'),[teacher,setTeacher]=useState<any>(null),[student,setStudent]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[className,setClassName]=useState('6º A'),[sound,setSound]=useState(false),[motion,setMotion]=useState(true),[online,setOnline]=useState(true);
 const lock=useRef(false);const qfocus=useRef<HTMLHeadingElement>(null);
 const load=useCallback(async()=>{const d=await api();setMe(d);setName(d.profile?.name||'');api(undefined,'?view=active').then(a=>setActive(a.run)).catch(()=>{});return d},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);setSound(localStorage.getItem('tufi-sound')==='true');setMotion(localStorage.getItem('tufi-motion')!=='false');if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[load]);
 useEffect(()=>{document.documentElement.dataset.motion=motion?'on':'off';localStorage.setItem('tufi-motion',String(motion));localStorage.setItem('tufi-sound',String(sound))},[motion,sound]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,[role=combobox],[role=switch]'))return;if(['ArrowDown','ArrowUp','ArrowLeft','ArrowRight'].includes(e.key)){const els=Array.from(document.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,[tabindex="0"]')).filter(x=>x.offsetParent!==null);const index=els.indexOf(document.activeElement as HTMLElement);if(els.length){e.preventDefault();els[(index+(e.key==='ArrowDown'||e.key==='ArrowRight'?1:-1)+els.length)%els.length].focus()}}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{if(view==='play')qfocus.current?.focus()},[view,run?.step]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const controller=new AbortController();try{Promise.resolve(mc.registerTool({name:'read_adventure_progress',description:'Read the current player adventure progress without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No arguments expected');return {name:me?.profile?.name||null,regions:me?.stats||[],view}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[me,view]);
 const act=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn()}catch(e:any){setError(e.message)}finally{lock.current=false;setBusy(false)}};
 const nav=(v:View)=>{setView(v);setError('');setNotice('');if(v==='map')load().catch(e=>setError(e.message));if(v==='history'){setStudent('');act(async()=>setHistory((await api(undefined,'?view=history')).runs))}if(v==='ranking')fetchRanking(selected,rankMode);if(v==='teacher')act(async()=>setTeacher(await api(undefined,'?view=teacher')))};
 const xp=(me?.stats||[]).reduce((n:number,r:any)=>n+Number(r.best),0),completed=(me?.stats||[]).filter((r:any)=>r.best>=400).length,level=gears.filter(g=>xp>=g.xp).at(-1)||gears[0],r=regions[selected],best=Number(me?.stats?.find((x:any)=>x.region===selected)?.best||0);
 function tone(correct:boolean){if(!sound)return;try{const AudioCtx=window.AudioContext||(window as any).webkitAudioContext;const ctx=new AudioCtx();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=correct?660:240;gain.gain.setValueAtTime(.07,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.2);osc.onended=()=>ctx.close()}catch{}}
 const start=()=>act(async()=>{if(!me?.profile){setView('profile');setNotice('Escolha seu nome de aventura para começar.');return}const d=await api({action:'start',region:selected});setRun(d);setFeedback(null);setChoice(null);setView('play')});
 const answer=(i:number)=>act(async()=>{if(feedback)return;setChoice(i);const d=await api({action:'answer',id:run.id,step:run.step,choice:i});setFeedback(d);tone(d.correct);if(d.done)await load()});
 const next=()=>{if(feedback.done){setRun({...run,finished:true});return}setRun({...run,step:feedback.step,count:feedback.count,question:feedback.next});setFeedback(null);setChoice(null)};
 const fetchRanking=(region:number,mode:string)=>act(async()=>{const d=await api(undefined,`?view=ranking&region=${region}&mode=${mode}`);setRanking(d.rows);if(d.message)setNotice(d.message)});
 const historyRows=()=>[['Região','Data','Acertos','Questões','Pontos','Tempo (s)'],...history.map(h=>[regions[h.region].name,new Date(h.started).toLocaleString('pt-BR'),h.correct,JSON.parse(h.answers).length,h.score,h.duration])];
 const icons=[Map,Backpack,ChartNoAxesCombined,Trophy];const navItems:[View,string][]=[['map','Aventura'],['inventory','Equipamentos'],['history','Meu progresso'],['ranking','Ranking']];
 return <div className="app-shell">
 <header className="topbar"><button className="brand" onClick={()=>nav('map')} aria-label="Tufi, início"><span className="brand-icon"><Compass/></span><span>TUFI<small>O ENIGMA DOS NÚMEROS</small></span></button><nav aria-label="Navegação principal">{navItems.map(([v,label],i)=>{const Icon=icons[i];return <button key={v} className={view===v?'nav active':'nav'} onClick={()=>nav(v)}><Icon size={19}/><span>{label}</span></button>})}</nav><button className="profile-chip" onClick={()=>nav('profile')}><span className="avatar">{me?.profile?.name?.slice(0,1).toUpperCase()||<UserRound size={20}/>}</span><span>{me?.profile?.name||'Seu perfil'}<small>{level.level}</small></span></button></header>
 <div className="utility"><span><span className="school-mark">6º</span> ANO <span className="divider">/</span> {me?.class?.name||'Sua jornada de matemática'}</span><div><span className="xp"><Star size={16}/>{xp} XP</span><button aria-label="Painel do professor" onClick={()=>nav('teacher')}><GraduationCap size={21}/></button><button aria-label="Configurações" onClick={()=>nav('settings')}><Settings size={21}/></button></div></div>
 {!online&&<div className="message"><WifiOff size={18}/>Você está sem conexão. <a href="/offline.html">Abrir treino offline</a></div>}
 {error&&<div className="message error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Fechar aviso">×</button></div>}{notice&&<div className="message" role="status">{notice}</div>}
 <main>
 {view==='map'&&<><div className="page-title"><div><p className="eyebrow">SUA PRÓXIMA DESCOBERTA</p><h1>Uma aventura. Infinitas possibilidades.</h1><p>Escolha um caminho. Use a matemática para abrir o próximo portal.</p></div><span className="chapter-count"><Compass size={20}/>{completed} / 6 regiões dominadas</span></div>
 <div className="adventure-grid"><section className="world" aria-label="Mapa das regiões"><img src="/world.webp" alt="Ilhas de fantasia com florestas, montanhas e portais dourados"/><div className="world-label"><span className="tiny-label">MAPA DO MUNDO</span><h2>O mundo de Tufi</h2></div><div className="map-nodes">{regions.map((reg,i)=><button key={i} onClick={()=>setSelected(i)} className={'map-node node-'+i+(selected===i?' selected':'')} aria-label={reg.name} aria-pressed={selected===i}><span>{(me?.stats||[]).some((s:any)=>s.region===i&&s.best>=400)?<Check/>:reg.symbol}</span><small>{i+1}. {reg.name.replace('Montanhas da ','').replace('Floresta das ','').replace('Reino dos ','').replace('Templo das ','').replace('Cavernas dos ','').replace('Fortaleza dos ','')}</small></button>)}</div><div className="map-caption"><Sparkles size={17}/>Cada descoberta começa com uma pergunta.</div></section>
 <aside className="mission-card"><div className="mission-top"><span className="eyebrow">REGIÃO {String(selected+1).padStart(2,'0')}</span><span className="pill">6º ano</span></div><div className="region-symbol" style={{color:r.color}}>{r.symbol}</div><h2>{r.name}</h2><p>{r.quest}</p><div className="mission-meta"><span><BookOpen size={17}/>{r.topic}</span><span><Compass size={17}/>5 desafios · no seu ritmo</span><span><Star size={17}/>Até 500 XP</span></div><div className="mission-progress"><span>Seu melhor resultado <strong>{best}/500</strong></span><Progress value={best/5}/></div><button className="primary full" onClick={start} disabled={busy}><Play size={19} fill="currentColor"/>{best?'Jogar novamente':'Iniciar missão'}<ChevronRight size={20}/></button>{active&&<button className="secondary full" style={{marginTop:12}} onClick={()=>{setSelected(active.region);setRun(active);setFeedback(null);setChoice(null);setView('play')}}>Continuar missão em andamento</button>}<p className="support">Aprenda com cada tentativa. Você pode melhorar sempre.</p></aside></div>
 <section className="region-strip" aria-label="Todas as regiões">{regions.map((reg,i)=><button key={i} className={'region-card '+(selected===i?'chosen':'')} onClick={()=>setSelected(i)}><span style={{color:reg.color}}>{reg.symbol}</span><div><small>REGIÃO {String(i+1).padStart(2,'0')}</small><strong>{reg.name}</strong></div>{(me?.stats||[]).some((s:any)=>s.region===i&&s.best>=400)&&<Check size={16}/>}</button>)}</section></>}
 {view==='play'&&run&&<section className="play-screen"><button className="back" onClick={()=>nav('map')}><ArrowLeft size={18}/>Voltar ao mapa</button>{run.finished?<div className="result-panel"><div className="result-icon"><Sparkles size={52}/></div><p className="eyebrow">MISSÃO CONCLUÍDA</p><h1>{feedback.count>=4?'O portal está aberto!':'Cada tentativa é uma descoberta.'}</h1><p>{feedback.count>=4?'Você restaurou a energia desta região.':'Revise as explicações e tente novamente para dominar a região.'}</p><div className="result-stats"><div><strong>{feedback.count}/5</strong><span>Acertos</span></div><div><strong>{feedback.score}</strong><span>Pontos na missão</span></div><div><strong>{feedback.duration}s</strong><span>Seu tempo</span></div></div><p>Seu XP total usa apenas o melhor resultado de cada região.</p><div className="actions"><button className="primary" onClick={()=>nav('map')}>Explorar o mapa<Compass size={18}/></button><button className="secondary" onClick={start}><RotateCcw size={18}/>Tentar novamente</button></div></div>:<><div className="battle-header"><div><p className="eyebrow">{r.name}</p><h1>{run.step===4?r.guardian:'Acenda os cristais do conhecimento'}</h1></div><span className="pill">{run.step===4?'DESAFIO DO GUARDIÃO':`ETAPA ${run.step+1} DE 5`}</span></div><div className={'battle-stage '+(feedback?.correct?'celebrate':'')}><div className="battle-crystals" aria-label={`${feedback?.count||run.count||0} cristais acesos`}>{Array.from({length:5},(_,i)=><span key={i} className={i<(feedback?.count||run.count||0)?'lit':''}>◇</span>)}</div><span className="knowledge-symbol" style={{color:r.color}}>{gears[me?.profile?.gear||0].symbol}</span><div className="lesson"><BookOpen size={20}/>{r.lesson}</div></div><div className="question-panel"><Progress value={(run.step+(feedback?1:0))*20}/><p className="eyebrow">{run.step===4?'O ÚLTIMO ENIGMA':'ENERGIA DO CONHECIMENTO'}</p><h2 ref={qfocus} tabIndex={-1}>{run.question.text}</h2><div className="answers">{run.question.options.map((o:string,i:number)=><button key={i} disabled={busy||!!feedback} onClick={()=>answer(i)} className={'answer '+(feedback?(feedback.correctIndex===i?'correct':choice===i?'incorrect':''):choice===i?'picked':'')}><span>{String.fromCharCode(65+i)}</span>{o}{feedback?.correctIndex===i&&<Check size={23}/>}</button>)}</div>{feedback&&<div className={'feedback '+(feedback.correct?'success':'retry')} role="status"><strong>{feedback.correct?'Muito bem! Um cristal ganhou energia.':'Errar faz parte do aprendizado.'}</strong><p>{feedback.explanation}</p><button className="primary" onClick={next}>{feedback.done?'Ver resultado':'Próximo desafio'}<ChevronRight size={19}/></button></div>}<p className="support">Use as setas para navegar e Enter para escolher. Não há limite de tempo.</p></div></>}</section>}
 {view==='inventory'&&<><Title tag="SUA EVOLUÇÃO" title="Ferramentas do conhecimento" text="Conquiste equipamentos ao melhorar seus resultados. Todos os itens são visuais."/><div className="inventory-grid">{gears.map((g,i)=><article className={'gear-card '+(xp<g.xp?'locked':'')} key={g.name}><span className="gear-symbol">{g.symbol}</span><span className="eyebrow">{g.level}</span><h2>{g.name}</h2><p>{g.xp===0?'Disponível desde o início':`${g.xp} XP para desbloquear`}</p><button className={me?.profile?.gear===i?'secondary':'primary'} disabled={busy||xp<g.xp||!me?.profile||me?.profile?.gear===i} onClick={()=>act(async()=>{await api({action:'gear',gear:i});await load();setNotice('Equipamento selecionado!')})}>{xp<g.xp?<><Lock size={17}/>Bloqueado</>:me?.profile?.gear===i?<><Check size={17}/>Equipado</>:'Equipar'}</button></article>)}</div><div className="panel"><h2>{level.level} · {xp} XP</h2><p>Domine uma região com pelo menos 4 acertos em 5. Seu equipamento aparece como símbolo de energia durante a aventura.</p></div></>}
 {view==='history'&&<><Title tag="CADA PASSO CONTA" title={student?`Histórico de ${student}`:'Meu progresso'} text="Seus resultados reais, com explicações para continuar aprendendo."/><div className="actions no-print"><button className="secondary" onClick={()=>exportCSV(historyRows(),'tufi-progresso.csv')}><Download size={17}/>Exportar CSV</button><button className="secondary" onClick={()=>window.print()}><Printer size={17}/>Imprimir / salvar PDF</button></div>{history.length===0?<Empty text="Sua história começa na primeira missão." action={()=>nav('map')}/>:<div className="history-list">{history.map(h=><details key={h.id} className="panel"><summary><span><strong>{regions[h.region].name}</strong><small>{new Date(h.started).toLocaleString('pt-BR')} · {h.done?'Concluída':'Em andamento'}</small></span><span>{h.correct}/{JSON.parse(h.answers).length} acertos · {h.score} pontos</span></summary><div className="history-answers">{JSON.parse(h.answers).map((a:any,i:number)=><div key={i}><strong>{i+1}. {a.text}</strong><p className={a.result.correct?'green':'orange'}>Sua resposta: {a.answer} · {a.result.correct?'Correta':'Vamos revisar'}</p><p>{a.result.explanation}</p></div>)}</div></details>)}</div>}</>}
 {view==='ranking'&&<><Title tag="CRESCENDO JUNTOS" title="Ranking da turma" text="Compare a mesma missão. Cada aluno aparece uma vez, com seu melhor resultado."/><div className="filters"><Select value={String(selected)} onValueChange={v=>{setSelected(Number(v));fetchRanking(Number(v),rankMode)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{regions.map((r,i)=><SelectItem value={String(i)} key={i}>{r.name}</SelectItem>)}</SelectContent></Select><Select value={rankMode} onValueChange={v=>{setRankMode(v);fetchRanking(selected,v)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="score">Melhor pontuação</SelectItem><SelectItem value="time">Desempenho e tempo</SelectItem></SelectContent></Select></div><p className="support left">{rankMode==='time'?'Mínimo de 80% de acertos. Mais acertos vêm primeiro; tempo desempata.':'Até 500 pontos por missão. O tempo desempata resultados iguais.'}</p>{ranking.length===0?<Empty text="Ainda não há resultados para esta turma e missão."/>:<div className="panel"><Table><TableHeader><TableRow><TableHead>Posição</TableHead><TableHead>Nome de aventura</TableHead><TableHead>Acertos</TableHead><TableHead>Pontos</TableHead><TableHead>Tempo</TableHead></TableRow></TableHeader><TableBody>{ranking.map((row,i)=><TableRow key={i}><TableCell><span className="position">{i+1}</span></TableCell><TableCell>{row.name}</TableCell><TableCell>{row.correct}/5</TableCell><TableCell className="gold">{row.score}</TableCell><TableCell>{row.duration}s</TableCell></TableRow>)}</TableBody></Table></div>}</>}
 {view==='profile'&&<div className="narrow"><Title tag="SEU LUGAR NESTA AVENTURA" title="Perfil do explorador" text="Use um apelido ou nome de aventura. Você pode alterá-lo depois."/><form className="panel form" onSubmit={e=>{e.preventDefault();act(async()=>{await api({action:'profile',name});await load();setNotice('Perfil salvo. Sua aventura está pronta!')})}}><label htmlFor="name">Nome de aventura</label><input id="name" autoComplete="nickname" minLength={2} maxLength={40} value={name} onChange={e=>setName(e.target.value)} required placeholder="Como quer ser chamado?"/><p>6º ano · {me?.class?.name||'Sem turma vinculada'}</p><button className="primary" disabled={busy}>Salvar perfil<Check size={18}/></button></form><form className="panel form" onSubmit={e=>{e.preventDefault();act(async()=>{await api({action:'join',code});await load();setNotice('Você entrou na turma!');setCode('')})}}><h2>Entrar em uma turma</h2><p>Peça o código ao seu professor. Trocar de turma não transfere resultados antigos para o ranking da nova sala.</p><label htmlFor="code">Código da turma</label><input id="code" maxLength={30} value={code} onChange={e=>setCode(e.target.value)} required placeholder="Código recebido na escola"/><button className="secondary" disabled={busy||!me?.profile}>Vincular turma</button></form>{!me&&<a className="primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar com ChatGPT</a>}</div>}
 {view==='settings'&&<div className="narrow"><Title tag="DO SEU JEITO" title="Configurações" text="Prepare a aventura para jogar no computador, celular ou televisão."/><div className="panel settings"><label htmlFor="sound"><span><Volume2/>Sons de resposta</span><Switch id="sound" checked={sound} onCheckedChange={setSound}/></label><label htmlFor="motion"><span><Sparkles/>Animações leves</span><Switch id="motion" checked={motion} onCheckedChange={setMotion}/></label><h2>Controle e acessibilidade</h2><p>Use Tab ou as setas para navegar e Enter para confirmar. Na TV Box, conecte um teclado ou controle que envie essas teclas.</p><h2>Treino sem internet</h2><p>Abra o treino uma vez com conexão. Ele ficará disponível neste navegador, se o dispositivo permitir. Os resultados ficam apenas neste aparelho e não entram no ranking.</p><a className="secondary" href="/offline.html"><WifiOff size={18}/>Abrir treino offline</a></div></div>}
 {view==='teacher'&&<><Title tag="ESPAÇO DO PROFESSOR" title="Aprendizagem em acompanhamento" text="Turmas vinculadas, histórico individual e relatórios com dados reais."/>{!me?.teacher?<div className="panel narrow"><ShieldCheck size={36}/><h2>Acesso autorizado pela escola</h2><p>Ser aluno ou possuir uma conta não libera acesso de professor. A escola precisa autorizar a identidade do responsável antes da criação de turmas.</p><p>Depois da autorização, este espaço permite criar turmas, entregar códigos e consultar somente os alunos vinculados.</p></div>:<><form className="panel inline-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api({action:'class',name:className});setTeacher(await api(undefined,'?view=teacher'));setNotice('Turma criada. Entregue o código aos seus alunos.')})}}><label htmlFor="class">Nova turma do 6º ano</label><input id="class" value={className} onChange={e=>setClassName(e.target.value)} maxLength={40} required/><button className="primary" disabled={busy}>Criar turma</button></form><div className="class-list">{teacher?.classes?.map((c:any)=><div className="panel" key={c.id}><h2>{c.name}</h2><p>Código de entrada: <strong>{c.code}</strong></p></div>)}</div><div className="actions no-print"><button className="secondary" onClick={()=>exportCSV([['Aluno','Turma','Missões concluídas','Acertos','Pontos acumulados nas tentativas'],...(teacher?.students||[]).map((s:any)=>[s.name,s.class_name,s.attempts,s.correct,s.score])],'tufi-turma.csv')}><Download size={17}/>Exportar CSV</button><button className="secondary" onClick={()=>window.print()}><Printer size={17}/>Imprimir / salvar PDF</button></div><div className="panel"><Table><TableHeader><TableRow><TableHead>Aluno</TableHead><TableHead>Turma</TableHead><TableHead>Missões</TableHead><TableHead>Acertos</TableHead><TableHead>Histórico</TableHead></TableRow></TableHeader><TableBody>{teacher?.students?.map((s:any)=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell>{s.class_name}</TableCell><TableCell>{s.attempts}</TableCell><TableCell>{s.attempts?Math.round(s.correct/(s.attempts*5)*100)+'%':'—'}</TableCell><TableCell><button className="secondary" onClick={()=>act(async()=>{setHistory((await api(undefined,'?view=history&student='+encodeURIComponent(s.id))).runs);setStudent(s.name);setView('history')})}>Ver histórico</button></TableCell></TableRow>)}</TableBody></Table>{!teacher?.students?.length&&<p>Ainda não há alunos vinculados.</p>}</div></>}</>}
 </main><footer><span>TUFI <span className="divider">/</span> Matemática é descobrir possibilidades.</span><span>Projeto para a E. E. Tufi Madi · Mirassol</span></footer>
 </div>
}
function Title({tag,title,text}:{tag:string;title:string;text:string}){return <div className="page-title"><div><p className="eyebrow">{tag}</p><h1>{title}</h1><p>{text}</p></div></div>}
function Empty({text,action}:{text:string;action?:()=>void}){return <div className="empty"><Compass size={42}/><h2>{text}</h2>{action&&<button className="primary" onClick={action}>Explorar o mapa</button>}</div>}
