'use client';
import {useState} from 'react';
export default function PasswordChange({required=false,onChanged}:{required?:boolean;onChanged?:(account:any)=>void}){
 const [current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setError('');setNotice('');if(password!==confirm){setError('As novas senhas precisam ser iguais.');return}setBusy(true);try{
  const r=await fetch('/api/auth',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'changePassword',currentPassword:current,password,confirmPassword:confirm}),signal:AbortSignal.timeout(15000)});
  const d:any=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível alterar sua senha.');setCurrent('');setPassword('');setConfirm('');setNotice(d.message);onChanged?.(d.account);
 }catch(e:any){setError(e.name==='TimeoutError'?'A conexão demorou demais. Tente novamente.':e.message)}finally{setBusy(false)}}
 return <section className="password-change"><h3>{required?'Escolha sua nova senha':'Alterar minha senha'}</h3><p>{required?'Você entrou com uma senha temporária. Crie uma senha só sua para continuar. Seu ID e seu progresso serão mantidos.':'Escolha uma senha de 10 a 128 caracteres. Seu ID continua o mesmo.'}</p><form className="form" onSubmit={submit}><label htmlFor="current-password">{required?'Senha temporária':'Senha atual'}</label><input id="current-password" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} maxLength={128} required/><label htmlFor="new-password">Nova senha</label><input id="new-password" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} maxLength={128} required/><label htmlFor="new-password-confirm">Confirmar nova senha</label><input id="new-password-confirm" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={10} maxLength={128} required/>{error&&<p className="message error" role="alert">{error}</p>}{notice&&<p className="message" role="status">{notice}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':required?'Salvar senha e continuar':'Salvar nova senha'}</button></form></section>
}
