export const regions = [
 {name:'Reino dos Números',topic:'Números naturais',symbol:'＋',color:'#f0b418',guardian:'Guardião do Portal',lesson:'Para somar, separe dezenas e unidades. Use multiplicação para grupos iguais e subtração para descobrir quanto falta.',quest:'Acenda os cinco cristais para abrir o portal do reino.'},
 {name:'Floresta das Frações',topic:'Frações e equivalências',symbol:'½',color:'#77d9aa',guardian:'Guardião das Pontes',lesson:'Frações equivalentes representam a mesma quantidade. Multiplique numerador e denominador pelo mesmo número.',quest:'Reconstrua as pontes e devolva a energia à floresta.'},
 {name:'Montanhas da Geometria',topic:'Formas e medidas',symbol:'△',color:'#9cbcfb',guardian:'Guardião dos Cristais',lesson:'Perímetro é a soma dos lados. A área de um retângulo é base × altura.',quest:'Alinhe os cristais geométricos para alcançar o cume.'},
 {name:'Templo das Operações',topic:'Expressões numéricas',symbol:'×',color:'#eab985',guardian:'Guardião do Templo',lesson:'A ordem importa: parênteses primeiro, depois multiplicação e divisão, depois adição e subtração.',quest:'Ative os mecanismos antigos do templo.'},
 {name:'Cavernas dos Desafios',topic:'Decimais e grandezas',symbol:'÷',color:'#b1a8f4',guardian:'Guardião das Medidas',lesson:'Um metro tem 100 centímetros. Ao somar decimais, alinhe as vírgulas.',quest:'Ilumine a caverna usando medidas e raciocínio.'},
 {name:'Fortaleza dos Enigmas',topic:'Revisão e raciocínio',symbol:'∞',color:'#efce6d',guardian:'Guardião do Conhecimento',lesson:'Leia o problema, escolha a operação e confira se o resultado faz sentido.',quest:'Reúna tudo o que aprendeu e liberte a energia do conhecimento.'},
 {name:'Reino da Divisibilidade',topic:'Múltiplos, divisores e números primos',symbol:'✦',color:'#74e5d1',guardian:'Guardião dos Divisores',lesson:'Um divisor forma grupos exatos, sem resto. Use as regras de divisibilidade para investigar números.',quest:'Decifre os números do portal secreto e estabilize o novo mundo.'}
];
export const gears=[
 {name:'Pulseira numérica',symbol:'＋',xp:0,level:'Aprendiz',bonus:'Revela uma dica curta do Tufi em cada desafio.'},
 {name:'Mochila do explorador',symbol:'÷',xp:350,level:'Explorador',bonus:'Abre uma dica ampliada com a estratégia da região.'},
 {name:'Compasso do estrategista',symbol:'△',xp:700,level:'Estrategista',bonus:'Elimina uma alternativa incorreta por desafio.'},
 {name:'Insígnia do conhecimento',symbol:'∞',xp:1050,level:'Capitão',bonus:'Permite revisar e trocar a resposta antes de confirmar.'},
 {name:'Cristal de Proteção',symbol:'◇',xp:1400,level:'Protetor',bonus:'Mostra um checklist para conferir o raciocínio antes de responder.'},
 {name:'Ampulheta Mágica',symbol:'⌛',xp:1750,level:'Mestre do Tempo',bonus:'Divide o desafio em três passos, sem limite de tempo.'},
 {name:'Mapa Antigo',symbol:'⌖',xp:2100,level:'Cartógrafo',bonus:'Revela a estratégia e o caminho matemático da região.'},
 {name:'Poção de Revisão',symbol:'⚗',xp:2450,level:'Alquimista',bonus:'Apresenta um exemplo resolvido parecido para orientar a resposta.'},
 {name:'Chave Dourada',symbol:'⚿',xp:2800,level:'Guardião',bonus:'Elimina duas alternativas incorretas por desafio.'},
 {name:'Caderno do Explorador',symbol:'▤',xp:2900,level:'Inventor',bonus:'Abre um rascunho para organizar suas contas em cada desafio.'},
 {name:'Lente dos Enigmas',symbol:'◉',xp:3000,level:'Investigador',bonus:'Amplia a pergunta e destaca os números para ajudar na leitura.'},
 {name:'Régua dos Múltiplos',symbol:'↔',xp:3200,level:'Pesquisador',bonus:'Abre uma tabela de múltiplos de 2 a 12 para consultar durante o desafio.'},
 {name:'Orbe do Sétimo Sinal',symbol:'✺',xp:3500,level:'Mestre dos Sete Mundos',bonus:'Reúne rascunho, lente de leitura e tabela de múltiplos em um só equipamento.'}
];
export const outfits=[
 {name:'Explorador clássico',xp:0,image:'/tufi-story-mascot.png',description:'O boné, os óculos azuis e o compasso que acompanham o Tufi desde o início.'},
 {name:'Cartógrafo das Trilhas',xp:1500,image:'/tufi-cartografo.png',description:'Colete verde-petróleo e mapa de viagem para descobrir novos caminhos.'},
 {name:'Guardião dos Cristais',xp:3000,image:'/tufi-guardiao.png',description:'Capa azul e detalhes dourados para celebrar a união dos seis cristais.'}
];
export type Question={text:string;options:string[];correct:number;explanation:string;hint?:string;bonus?:{kind:'eliminate'|'golden-key';indices:number[]}};
function rand(n:number){const v=new Uint32Array(1);crypto.getRandomValues(v);return v[0]%n}
export function makeQuestion(region:number,stage:number):Question{
 const a=rand(8)+3,b=rand(6)+2;let text='',answer='',explanation='',wrong:string[]=[];
 const number=(t:string,n:number,e:string)=>{text=t;answer=String(n);explanation=e;wrong=[String(n+1),String(n+3),String(Math.max(0,n-2))]};
 if(region===0){if(stage<2)number(`${a*10} + ${b*3} = ?`,a*10+b*3,`Some as dezenas e as unidades: ${a*10} + ${b*3} = ${a*10+b*3}.`);else if(stage<4)number(`Há ${a} caixas com ${b} cristais em cada uma. Quantos cristais há?`,a*b,`${a} grupos de ${b}: ${a} × ${b} = ${a*b}.`);else number(`O portal precisa de ${a*b} cristais. Já tem ${a}. Quantos faltam?`,a*b-a,`Subtraia o que já existe: ${a*b} − ${a} = ${a*b-a}.`)}
 if(region===1){if(stage%2===0){text=`Qual fração equivale a 1/${b}?`;answer=`${a}/${a*b}`;wrong=[`${a}/${a*b+1}`,`1/${b+1}`,`${a+1}/${a*b}`];explanation=`Multiplique as duas partes por ${a}: 1/${b} = ${a}/${a*b}.`;}else number(`Quanto é 1/${b} de ${a*b}?`,a,`Divida o total em ${b} partes iguais: ${a*b} ÷ ${b} = ${a}.`)}
 if(region===2){if(stage===0){text='Quantos lados tem um hexágono?';answer='6';wrong=['5','7','8'];explanation='O hexágono é um polígono de seis lados.';}else if(stage===3){text='Quanto mede um ângulo reto?';answer='90°';wrong=['45°','180°','360°'];explanation='Um ângulo reto mede 90°, como o canto de um quadrado.';}else if(stage%2)number(`Um retângulo mede ${a} m por ${b} m. Qual é o perímetro, em metros?`,2*(a+b),`Some os quatro lados: ${a} + ${b} + ${a} + ${b} = ${2*(a+b)} m.`);else number(`Um retângulo mede ${a} m por ${b} m. Qual é a área, em m²?`,a*b,`Área = base × altura = ${a} × ${b} = ${a*b} m².`)}
 if(region===3){if(stage%2)number(`(${a} + ${b}) × 2 = ?`,(a+b)*2,`Parênteses primeiro: ${a+b} × 2 = ${(a+b)*2}.`);else number(`${a} + ${b} × 2 = ?`,a+b*2,`Multiplique antes de somar: ${a} + ${b*2} = ${a+b*2}.`)}
 if(region===4){if(stage%2)number(`${a} metros equivalem a quantos centímetros?`,a*100,`Cada metro tem 100 cm: ${a} × 100 = ${a*100} cm.`);else {text=`${a},50 + ${b},25 = ?`;answer=`${a+b},75`;wrong=[`${a+b},25`,`${a+b+1},75`,`${a+b},50`];explanation=`Some as partes inteiras e os centésimos: ${a+b} + 0,75 = ${answer}.`;}}
 if(region===5){if(stage<2)number(`Divida ${a*b} cristais igualmente entre ${b} portais. Quantos vão em cada um?`,a,`${a*b} ÷ ${b} = ${a}.`);else if(stage<4)number(`Uma sequência começa em ${a} e aumenta de ${b} em ${b}: ${a}, ${a+b}, ${a+2*b}, ... Qual é o próximo número?`,a+3*b,`Adicione ${b} ao último número: ${a+2*b} + ${b} = ${a+3*b}.`);else number(`Uma sala tem ${a} fileiras com ${b} lugares. ${b} lugares estão vazios. Quantas pessoas estão sentadas?`,a*b-b,`Primeiro calcule os lugares: ${a} × ${b} = ${a*b}. Depois subtraia os vazios: ${a*b} − ${b} = ${a*b-b}.`)}
 if(region===6){if(stage===0){const n=a*b;text=`Qual número é divisor de ${n}?`;answer=String(b);wrong=[String(n+1),String(n+2),String(n+3)];explanation=`${b} é divisor de ${n}, pois ${n} ÷ ${b} = ${a}, sem resto.`;}else if(stage===1){const n=(a*2)*5;text=`${n} é divisível por 5?`;answer='Sim, porque termina em 0 ou 5';wrong=['Não, porque é par','Sim, porque a soma dos algarismos é par','Não, porque é maior que 10'];explanation=`Todo número terminado em 0 ou 5 é divisível por 5. Portanto, ${n} é divisível por 5.`;}else if(stage===2){const n=a*3;text=`Qual é um múltiplo de ${a}?`;answer=String(n);wrong=[String(n+1),String(n+2),String(Math.max(1,n-a+1))];explanation=`${n} é múltiplo de ${a}, pois ${a} × 3 = ${n}.`;}else if(stage===3){text='Qual destes números é primo?';answer='13';wrong=['12','15','21'];explanation='13 só pode ser dividido exatamente por 1 e por 13, por isso é primo.';}else{const n=a*b;text=`O portal tem ${n} cristais. Eles podem ser separados igualmente em ${b} grupos?`;answer=`Sim, ${a} em cada grupo`;wrong=['Não, sobra 1',`Sim, ${a+1} em cada grupo`,`Não, ${n} é primo`];explanation=`Sim. ${n} ÷ ${b} = ${a}, então não sobra nenhum cristal.`;}}
 const options=[answer,...wrong];for(let i=options.length-1;i>0;i--){let j=rand(i+1);[options[i],options[j]]=[options[j],options[i]]}const hints=[stage<2?'Separe dezenas e unidades. Some cada parte e reúna os resultados.':stage<4?'Cada caixa tem a mesma quantidade. Que operação representa grupos iguais?':'Compare o total necessário com o que já está no portal. O que falta?',stage%2===0?'Observe o numerador. Pelo que ele foi multiplicado? Faça o mesmo com o denominador.':'Divida o total pelo número de partes iguais.',stage===0?'Hexa é um prefixo usado para seis. Conte os lados.':stage===3?'Pense no canto de um quadrado.':'A pergunta pede contorno (somar lados) ou superfície (multiplicar medidas)?',stage%2?'Resolva primeiro o que está dentro dos parênteses.':'Faça a multiplicação antes da adição.',stage%2?'Cada metro contém cem centímetros.':'Alinhe as vírgulas e some inteiros e centésimos separadamente.',stage<2?'Repartir igualmente significa dividir o total pelo número de grupos.':stage<4?'Subtraia dois termos vizinhos para descobrir quanto a sequência cresce.':'Calcule todos os lugares e depois retire os vazios.',stage<2?'Um divisor divide o número sem deixar resto. Teste a divisão.':stage<4?'Múltiplos aparecem ao multiplicar um número por 1, 2, 3 e assim por diante.':'Separe em grupos iguais e verifique se sobra algum cristal.'];return {text,options,correct:options.indexOf(answer),explanation,hint:hints[region]};
}
export function publicQuestion(q:Question){return {text:q.text,options:q.options,hint:q.hint||'Leia com calma e separe os dados antes de escolher a operação.',eliminated:q.bonus?.indices??[]}}
export function scoreRun(correct:number){return correct*100}
