'use client';
import {useEffect,useRef,useState} from 'react';
import {Mail,ShieldCheck,ArrowLeft} from 'lucide-react';
export default function AccountFlow(){
 const [action,setAction]=useState('forgot'),[ready,setReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[done,setDone]=useState(false);
 const token=useRef('');
 useEffect(()=>{const p=new URLSearchParams(location.hash.slice(1));const kind=p.get('action');if(kind==='verify'||kind==='reset'){setAction(kind);token.current=p.get('token')||'';history.replaceState(null,'','/conta');if(!/^[a-f0-9]{64}$/.test(token.current))setError('Link inválido. Solicite outro e-mail.')}setReady(true)},[]);
 return <main className="recovery-shell"><section className="panel recovery-card"><a className="back" href="/"><ArrowLeft size={18}/>Voltar ao login</a><div className="region-symbol">{action==='forgot'?<Mail size={38}/>:<ShieldCheck size={38}/>}</div><p className="eyebrow">TUFI · SUA CONTA</p><h1>{action==='forgot'?'Esqueceu sua senha?':action==='reset'?'Crie uma nova senha':'Confirme seu e-mail'}</h1><p>{action==='forgot'?'Informe o e-mail que você já confirmou na sua conta. Enviaremos um link para você escolher outra senha.':action==='reset'?'Escolha uma senha de 10 a 128 caracteres. Ao concluir, suas sessões anteriores serão encerradas.':'Digite a senha da conta do jogo que solicitou este vínculo. A confirmação do e-mail não substitui a autorização do administrador.'}</p>{error&&<p className="access-alert error" role="alert">{error}</p>}{notice&&<p className="access-alert" role="status">{notice}</p>}{!done&&ready&&<form className="form" onSubmit={async e=>{e.preventDefault();if(busy)return;setError('');if(action==='reset'&&password!==confirm){setError('As senhas precisam ser iguais.');return}setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email,password,token:token.current})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setNotice(d.message);setDone(true);setPassword('');setConfirm('');token.current=''}catch(e:any){setError(e.message||'Não foi possível concluir. Tente novamente.')}finally{setBusy(false)}}}>{action==='forgot'?<><label htmlFor="recovery-email">E-mail da conta</label><input id="recovery-email" type="email" autoComplete="email" maxLength={254} required value={email} onChange={e=>setEmail(e.target.value)}/></>:<><label htmlFor="recovery-password">{action==='reset'?'Nova senha':'Senha atual do jogo'}</label><input id="recovery-password" type="password" autoComplete={action==='reset'?'new-password':'current-password'} required minLength={10} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/>{action==='reset'&&<><label htmlFor="recovery-confirm">Repita a nova senha</label><input id="recovery-confirm" type="password" autoComplete="new-password" required minLength={10} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></>}</>}<button className="primary full" disabled={busy}>{busy?'Aguarde…':action==='forgot'?'Enviar link de recuperação':action==='reset'?'Salvar nova senha':'Confirmar e-mail'}</button></form>}{done&&<a className="primary full" href="/">Voltar ao login</a>}{action==='forgot'&&<p className="support left">Ainda não vinculou um e-mail? Entre com seu ID e senha e cadastre o endereço no perfil. Se também esqueceu a senha, fale com o administrador; não há recuperação automática sem e-mail confirmado.</p>}{action!=='forgot'&&!done&&<p className="support left">Abra novamente o link do e-mail se precisar recarregar esta página.</p>}</section></main>
}
