import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),name:text('name').notNull(),classId:text('class_id'),email:text('email').notNull().default(''),role:text('role').notNull().default('student'),requestedRole:text('requested_role').notNull().default('student'),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(0),gear:integer('gear').notNull().default(0)});
export const classes=sqliteTable('classes',{id:text('id').primaryKey(),name:text('name').notNull(),teacher:text('teacher').notNull(),code:text('code').notNull().unique()},t=>[index('idx_classes_teacher').on(t.teacher)]);
export const runs=sqliteTable('runs',{id:text('id').primaryKey(),userId:text('user_id').notNull(),classId:text('class_id'),region:integer('region').notNull(),questions:text('questions').notNull(),answers:text('answers').notNull().default('[]'),step:integer('step').notNull().default(0),started:integer('started').notNull(),correct:integer('correct').notNull().default(0),score:integer('score').notNull().default(0),duration:integer('duration').notNull().default(0),done:integer('done').notNull().default(0)},t=>[index('idx_runs_user').on(t.userId),index('idx_runs_class_region').on(t.classId,t.region,t.done)]);

export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),target:text('target').notNull(),action:text('action').notNull(),details:text('details').notNull(),created:integer('created').notNull()},t=>[index('idx_audit_created').on(t.created)]);
export const accounts=sqliteTable('accounts',{userId:text('user_id').primaryKey(),loginId:text('login_id').notNull().unique(),passwordHash:text('password_hash').notNull(),email:text('email').unique(),emailVerified:integer('email_verified').notNull().default(0),created:integer('created').notNull()});
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull(),expires:integer('expires').notNull()},t=>[index('idx_sessions_expires').on(t.expires),index('idx_sessions_user').on(t.userId)]);
export const authLimits=sqliteTable('auth_limits',{bucket:text('bucket').primaryKey(),hits:integer('hits').notNull(),expires:integer('expires').notNull()});
export const emailTokens=sqliteTable('email_tokens',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),email:text('email').notNull(),expectedHash:text('expected_hash').notNull(),expires:integer('expires').notNull(),consumedBy:text('consumed_by')},t=>[index('idx_email_tokens_user').on(t.userId),index('idx_email_tokens_expiry').on(t.expires)]);
