(function(){
const $=s=>document.querySelector(s);let step=0,correct=0,region=0,question,answered=false,finished=false;
regions.forEach((r,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=r.name;$('#region').append(o)});
function show(){answered=false;question=makeQuestion(region,step);$('#step').textContent=`Desafio ${step+1} de 5`;$('#question').textContent=question.text;$('#options').replaceChildren();$('#message').classList.add('hide');$('#next').classList.add('hide');question.options.forEach((o,i)=>{const b=document.createElement('button');b.textContent=o;b.onclick=()=>{if(answered||finished)return;answered=true;const ok=i===question.correct;if(ok)correct++;$('#options').querySelectorAll('button').forEach(el=>el.disabled=true);$('#message').textContent=(ok?'Muito bem! ':'Errar faz parte do aprendizado. ')+question.explanation;$('#message').classList.remove('hide');$('#next').textContent=step===4?'Concluir treino':'Próximo desafio';$('#next').classList.remove('hide')};$('#options').append(b)});$('#question').focus()}
$('#start').onclick=()=>{region=Number($('#region').value);step=0;correct=0;finished=false;$('#game').classList.remove('hide');show()};
function readHistory(){try{const a=JSON.parse(localStorage.getItem('tufi-offline-history')||'[]');return Array.isArray(a)?a.filter(x=>x&&Number.isInteger(x.region)&&regions[x.region]&&Number.isInteger(x.correct)&&x.correct>=0&&x.correct<=5).slice(-100):[]}catch{return []}}
function saved(){const a=readHistory(),last=a[a.length-1];$('#stored').textContent=last?`${a.length} treinos guardados neste navegador. Último: ${last.correct}/5 acertos em ${regions[last.region].name}.`:''}
$('#next').onclick=()=>{if(!answered||finished)return;if(step<4){step++;show();return}finished=true;$('#question').textContent=`Treino concluído: ${correct}/5 acertos!`;$('#options').replaceChildren();$('#message').textContent='Continue praticando. Este resultado não será enviado ao ranking.';$('#next').classList.add('hide');try{const a=readHistory();a.push({region,correct,date:Date.now()});localStorage.setItem('tufi-offline-history',JSON.stringify(a.slice(-100)));saved()}catch{$('#stored').textContent='O treino terminou, mas este navegador não permitiu guardar o resultado.'}};saved();
$('#download').onclick=()=>{const clean=document.documentElement.cloneNode(true);clean.querySelector('#region').replaceChildren();clean.querySelector('#options').replaceChildren();clean.querySelector('#game').classList.add('hide');clean.querySelector('#stored').textContent='';clean.querySelector('#question').textContent='';clean.querySelector('#message').textContent='';const blob=new Blob(['<!doctype html>\n'+clean.outerHTML],{type:'text/html;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='Tufi-Treino-Offline.html';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
const timeout=(promise,ms)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),ms))]);
async function prepare(){
 if(location.protocol==='file:'){$('#cache').textContent='Arquivo offline: você pode jogar sem conexão. Guarde este arquivo no aparelho.';return}
 if(!('serviceWorker'in navigator)||!('caches'in window)){$('#cache').textContent='O navegador não permite preparar o modo offline. Use “Baixar treino” e abra o arquivo no aparelho.';return}
 try{const registration=await timeout(navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}),10000);await registration.update().catch(()=>{});await timeout(navigator.serviceWorker.ready,10000);
 const response=await timeout(fetch('/api/practice',{cache:'no-store',credentials:'same-origin'}),10000);if(!response.ok||response.redirected)throw new Error('response');const html=await response.clone().text();if(!html.includes('data-tufi-practice="v2"'))throw new Error('not-practice');await(await caches.open('tufi-practice-v2')).put('/api/practice',response);$('#cache').textContent='Treino preparado para uso offline neste navegador. Você também pode baixar uma cópia.';
 }catch{$('#cache').textContent='Não foi possível preparar o navegador para uso offline. O treino funciona agora; baixe uma cópia para jogar sem internet.'}}
prepare();
document.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight'].includes(e.key)||e.target.tagName==='SELECT')return;const els=[...document.querySelectorAll('a,button:not(:disabled),select')].filter(x=>x.offsetParent);if(!els.length)return;e.preventDefault();const i=els.indexOf(document.activeElement),d=['ArrowDown','ArrowRight'].includes(e.key)?1:-1;els[(i+d+els.length)%els.length].focus()});
})();
