import fs from 'node:fs';import ts from 'typescript';
let content=ts.transpileModule(fs.readFileSync('lib/content.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2019,module:ts.ModuleKind.ES2022}}).outputText.replace(/export /g,'');
content=content.replace('crypto.getRandomValues(v);',"if(globalThis.crypto?.getRandomValues)globalThis.crypto.getRandomValues(v);else v[0]=Math.floor(Math.random()*4294967296);");
let html=fs.readFileSync('scripts/offline/template.html','utf8').replace('<html lang="pt-BR">','<html lang="pt-BR" data-tufi-practice="v2">').replace('href="/"','href="https://tufi-enigma-numeros.oryon244.chatgpt.site"').replace('<script type="module" src="/offline.js"></script>','<script>'+content+'\n'+fs.readFileSync('scripts/offline/ui.js','utf8')+'</script>').replace('<footer><small','<p><button id="download">Baixar treino</button></p><footer><small');
fs.writeFileSync('public/offline.html',html);fs.writeFileSync('lib/offline-document.ts','// Generated by scripts/build-offline.mjs\nexport const offlineDocument='+JSON.stringify(html)+';\n');
console.log('Built self-contained offline document.');
